### ISSUE TITLE
Code standards contributing

### ISSUE THREAD

**Issue by eddieajau** [swagger-api/swagger-node#137]
I'm just wondering what the code standards are for code contribution (that is, indenting, braces, white-space, etc).

Also, with testing is there a strong attachment to using BDD style? I actually really like the `exports` style that Mocha supports because the code navigators can parse that really nicely (I find it really hard to navigate around a sea of `describe` calls). I'm also a fan of good old `assert` (PHP background) but I'm more than happy to go with the flow.

Thanks in advance.

**Comment by fehguy** [comment]
linting is now part of #209
