### ISSUE TITLE
Is there a way for enabling router middleware?

### ISSUE THREAD

**Issue by bjrmatos** [swagger-api/swagger-node#150]
With express i can:

```js
app.get('/index', middleware1, middleware2, function(req, res) {
  // Logic here
});
```

Is there a way to do so in swagger routes/resources?

**Comment by fehguy** [comment]
Take a look here for the proposed direction for version 3.0:

https://github.com/swagger-api/swagger-node-express/issues/180#issuecomment-83224535

**Comment by plumpNation** [comment]
I use the [middleware-flow module](https://www.npmjs.com/package/middleware-flow) for this, specifically the 'series'.

**Comment by fehguy** [comment]
This is handled in #209
