### ISSUE TITLE
subPath UI example?

### ISSUE THREAD

**Issue by jimgeiger** [swagger-api/swagger-node#163]
Is there a working UI example of using the [receommended subpath approach](https://github.com/wordnik/swagger-node-express#mapping-swagger-to-subpaths)?  In particular how to adjust the relevant UI paths?  I saw the [closed issue #34](https://github.com/wordnik/swagger-node-express/issues/34) but don't understand the concluding comment.  Thanks for your help.

**Comment by fehguy** [comment]
Take a look at #209 for this support.
