### ISSUE TITLE
Reduce barrier to entry

### ISSUE THREAD

**Issue by newmanw** [swagger-api/swagger-node#185]
This looks like a great framework!  There is always a but right ;)

I have a few existing nodejs applications that server out routes via express.  I would love to serve my api docs as swagger and recently started looking at my options.  This lib is awesome if you are starting a new application with node/express and build this in.  However if you have an existing application it requires extensive rework.

One idea would be to use the middleware framework, imho something like this would make it much easier to get started, and also easier to remove, why would I ever remove right ;) 

Existing route, which would need to be completely reworked
```javascript
  // get all uses
  app.get(
    function(req, res) {
      var users = User.getUsers(err, users)
        res.json(users);
      });
  });
```

New route with a simple middleware function to add swagger, everything else remains intact
```javascript
  // get all uses
  app.get(
    '/api/users',
    swagger({
    "description" : "Operations about pets",
    "path" : "/users",
    "notes" : "Returns all users",
    "summary" : "Find all users",
    "method": "GET",
    "parameters" : [],
    "type" : "User",
    "errorResponses" : [],
    "nickname" : "getUsers"
    }),
    function(req, res) {
      var users = User.getUsers(err, users)
        res.json(users);
      });
  });
```

Maybe this is outside the scope of this project as the design has already been done.  Could also be that is was considered and thrown out due to reasons I don't understand. Maybe something like this is not possible.

**Comment by Freyert** [comment]
+1 Could probably even take it further and do away with redundancies and have swagger figure out from express the HTTP method and path.

**Comment by fehguy** [comment]
Take a look here for the proposed direction for version 3.0:

https://github.com/swagger-api/swagger-node-express/issues/180#issuecomment-83224535

**Comment by fehguy** [comment]
This is handled in #209
