### ISSUE TITLE
How to define body param as required?

### ISSUE THREAD

**Issue by royts** [swagger-api/swagger-node#187]
hi,
in my resources definition I have a POST endpoint to create an entity.
I didn't saw any documentation about body params, but i tried `swagger.bodyParam` and it worked.

I wonder, how can I define some properties as required and return 404 if they are not sent?

here is my endpoint definition:

```JavaScript
createNew: {
    'spec': {
      "description": "Operations about swimmer",
      "path": "/swimmer",
      "notes": "",
      "summary": "Create a new swimmer",
      "method": "POST",
      "parameters": [
        swagger.bodyParam("swimmer", "", "Swimmer")

      ],
      "type": "Swimmer",
      "errorResponses": [swagger.errors.invalid('id'), swagger.errors.notFound('swimmer')],
      "nickname": "createSwimmer",
      produces: ["application/json"]
    },
    'action': function (req, res, next) {
    // do something - don't arrive here is some properties are not sent
      res.sendStatus(200);
    }
  }
```

**Comment by fehguy** [comment]
Hi, you can make a parameter required, and the UI will not allow you to submit without it being passed.  The server, however, is up to you to throw the 404 (or more appropriately 400) if it's not passed outside of swagger ui.

**Comment by fehguy** [comment]
This is handled in #209  The spec is the source of truth
