### ISSUE TITLE
#stopWithError always returns status 500 - internal server error

### ISSUE THREAD

**Issue by andyskw** [swagger-api/swagger-node#201]
The current version of swagger always throws `{'message': 'internal error', 'code': 500}` when #stopWithError(res, error) is called.

I think, this is an issue, and if so, I'd give a PR to fix it, as currently I am not able to use swagger to handle any errors other than the hardcoded ones. :)

**Comment by fehguy** [comment]
That is really only invoked with building the resource listing or api declaration.  Are you seeing otherwise?  Per this:  https://github.com/swagger-api/swagger-node-express#error-handling swagger is not consuming errors found when executing your operations, unless you've configured it to do so.

**Comment by fehguy** [comment]
This is handled in #209
