### ISSUE TITLE
Lib usage

### ISSUE THREAD

**Issue by yarax** [swagger-api/swagger-node#204]
Sorry, it's not an issue, but I haven't got a response on SO. So it my thoughts about lib and maybe you will dispel my doubts.

* Why should I use methods like addGet/addPost and split my controller by HTTP methods
* Why should I involve models to routing?
* I can use validators for authentication, but I have to choose some paths, that should be protected there. It duplicates logic, that stores in swagger json file.

Isn't it the right way to have a static swagger.json and build Express routes on it? Or maybe I don't understand some practics

**Comment by fehguy** [comment]
Hi, take a look here:

https://groups.google.com/forum/#!topic/swagger-swaggersocket/8aZZk5wroeg

We're redoing how this library works very soon.

**Comment by fehguy** [comment]
This is handled in #209
