### ISSUE TITLE
problem with file upload on M2

### ISSUE THREAD

**Issue by marcingasior** [swagger-api/swagger-node#206]
Hi Guys,

I found issue trying to upload file with latest code base https://github.com/swagger-api/swagger-node-express/blob/master/swagger-ui/swagger-ui.js on line 2057 you try to call window.authorization.apply() which is broken.

First of all you always set window.authorization on line 212, and then on 2057 you call apply on an object.

So either you need to call window.authorization.add.apply on 2057 or use some condition to add authorization to window.

Let me know, if you need more help.

Regards,
Marcin

**Comment by fehguy** [comment]
This is handled in #209
