### ISSUE TITLE
pre-condition callbacks

### ISSUE THREAD

**Issue by spazard1** [swagger-api/swagger-node#208]
In express, it is possible to add preconditions to routes when you declare the route. From the express documentation:
app.get('/example/b', function (req, res, next) {
  console.log('response will be sent by the next function ...');
  next();
}, function (req, res) {
  res.send('Hello from B!');
});

In swagger-node-express, you send in a 'spec' and 'action' to all of the addGet, addPost, etc. methods. Is there a way of adding these route preconditions in swagger-node-express?

**Comment by fehguy** [comment]
This is handled in #209
