### ISSUE TITLE
Deprecate swagger 1.x support, add spec-driven implementation

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-node#209]
The swagger-node-express project was originally built exclusively for express, and lacked proper middleware support.  During the transition to the [Swagger 2.0 Spec](https://github.com/swagger-api/swagger-spec), we decided that a complete rewrite of this project was in order to both update the integration techniques as well as support swagger 2.0 natively.

#207 adds full support for swagger 2.0 and a spec-driven lifecycle.

**Comment by fehguy** [comment]
Merged

**Comment by oliverhr** [comment]
Is there documentation available about the use of any of this features ?
