### ISSUE TITLE
"Swagger project edit" inside vagrant box

### ISSUE THREAD

**Issue by nikolasleblanc** [swagger-api/swagger-node#210]
Hey, trying to use swagger to build an api that's inside a vagrant box.

```
Swagger project edit
```

from inside that vagrant box fails because it can't find a default browser - naturally, we're in a terminal window and inside a guest machine. 

Anyway to just start up the server without trying to open a browser automatically, so I can forward the ports to my host machine and access the editor from there?

**Comment by theganyo** [comment]
Hey @nikolasleblanc!

You bet! Check out the --silent option:

$ swagger project edit -h

  Usage: edit [options] [directory]

  open Swagger editor for this project or the specified project directory

  Options:

    -h, --help   output usage information
    -s --silent  do not open the browser

**Comment by nikolasleblanc** [comment]
Ah geez, perfect. Thanks for pointing that out.

**Comment by theganyo** [comment]
No worries! :)
