### ISSUE TITLE
How to setup a post request for 'hello_world'

### ISSUE THREAD

**Issue by skyserpent** [swagger-api/swagger-node#214]
I'm using Express skeleton of swagger-node and I'm running into a problem when it comes to using POST. I get the get to work fine (which comes with the hello world skeleton) but when I try to change the 'get' in '/hello' to 'post' this is the error I get:

```
Error: Response validation failed: invalid content type (text/html).
```

What's the problem here I thought it should be as easy as changing 'get' to 'post' - I also did not tamper with the 'hello_world' controller so I don't understand why it's shooting me that error when it's supposed to return a JSON object.

**Comment by prabhatjha** [comment]
It should be easy. :-)  Since it's a POST request, you have to specify content-type because that's what hello world swagger defines in Consume (Line #16). Try 

curl  -X POST -H "Content-Typjson"  http://127.0.0.1:10010/hello?name=skyserpent

**Comment by skyserpent** [comment]
I was doing that but I realized it was a small error on my part. Closing this issue.
