### ISSUE TITLE
Setting response status in express

### ISSUE THREAD

**Issue by plingampally** [swagger-api/swagger-node#216]
I've started a new project using `swagger project create` and I am using the editor to change the YAML, so I know it's valid. 

**My Question:** How do I send back an error (400) response that's different than my normal (200) response. Since my 200 response is an array of strings, and my 400 response is just a string. In my current implementation i'm getting `Error: Response validation failed: failed schema validation`. 

This is what my swagger looks like: 
```yaml
/trustedfields:
  x-swagger-router-controller: metadata
  get:
    description: Returns the trusted fields for a given test field
    operationId: trustedFields 
    parameters:
      - name: testfield
        in: query
        description: Field to be tested against
        required: true
        type: string
    responses:
      200:
        description: Success
        schema:
          type: array
          items:
            $ref: "#/definitions/Path" 
      400:
        description: Error
        schema: 
          type: string
      default:
        description: Error
        schema: 
          $ref: "#/definitions/ErrorResponse"
```
In my controller file I've added `res.status(400);` but that did not seem to work. When I tried to use `res.sendStatus(400)` I was seeing almost the correct response, but only the first few characters of the response message.  

My controller function 

```javascript
function testFields(req, res) {
  var returnData;
	if(req.query.testfield) {
		returnData = [
				"/Test/Path/Example/Data"
			];
  		res.status(200).json(returnData);
	} else {
		returnData = "Error: invalid test field";
  		res.status(400).json(returnData);
	}
}
```

**Comment by joostfarla** [comment]
In order to improve consistency and to make the client able to do something with the error response, I would recommend to wrap the error message in a JSON object. To get there, you would change the definition like this:

```yaml
        "400":
          description: Error
          schema:
            type: object
```

And return the correct error response like this:

```js
res.status(400).json({'message': returnData});
```

**Comment by plingampally** [comment]
Hi @joostfarla even when I am wrapping the error response in an object, I am noticing that the status code that is being sent is always 200. This is the output from my logs: 

```
GET /v1/trustedfields?testfield=asf 200 10.741 ms - -
GET /v1/trustedfields?testfield= 200 3.124 ms - -
```

**Comment by theganyo** [comment]
@plingampally can you update your modules and try again? It's possible you're hitting a bug in the connect stuff that was recently addressed.

**Comment by plingampally** [comment]
@theganyo that fixed it! thanks for helping me!
