### ISSUE TITLE
Invalid json in POST

### ISSUE THREAD

**Issue by plingampally** [swagger-api/swagger-node#218]
I'm having trouble getting a POST route working. The error i'm receiving is: `Error: invalid json
    at parse (/Users/plingampally/XXXX/XXXX/XXXX/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/body-parser/lib/types/json.js:79:15)`

This is happening even when I send in valid JSON or strings. My controller is just sending back a simple string without even looking at the body.    

I've set up my swagger yaml like this:
```yaml
/errorcheck:
    x-swagger-router-controller: errorcheck
    post:
      description: Runs an error check against a given test field 
      operationId: errorcheck
      parameters:
        - name: param1
          in: body
          description: description
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Successs
          schema:
            type: string
        default:
          description: Error
          schema: 
            $ref: "#/definitions/ErrorResponse" 
```

I'd really appreciate an example of how to create a POST route.

**Comment by prabhatjha** [comment]
Can you post your complete swagger and curl request pls? You can see a post example at http://playground.apistudio.io/bfdc2968-06fb-438a-9785-6134d3d87ed7# and when you click on try-it, you can see how payload is getting sent.

**Comment by plingampally** [comment]
Hi @prabhatjha the link you posted did not have a post example, it only had one get request. 

here is my full swagger:
```yaml
swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:3000
# basePath prefixes all resource paths 
basePath: /v1
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        200:
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /listtestfields:
    x-swagger-router-controller: metadata
    get:
      description: Returns all the test fields
      operationId: listTestFields
      responses:
        200:
          description: Success 
          schema: 
            type: array
            items: 
              $ref: "#/definitions/foo" 
        default:
          description: Error
          schema: 
            $ref: "#/definitions/ErrorResponse" 
  /trustedfields:
    x-swagger-router-controller: metadata
    get:
      description: Returns the trusted fields for a given test field
      operationId: trustedFields 
      parameters:
        - name: testfield
          in: query
          description: Field to be tested against
          required: true
          type: string
      responses:
        "200":
          description: Successs
          schema:
            type: array
            items:
              $ref: "#/definitions/foo" 
        "400":
          description: Invalid Test Field
          schema: 
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema: 
            $ref: "#/definitions/ErrorResponse"
  /errorcheck:
    x-swagger-router-controller: errorcheck
    post:
      description: Runs an error check against a given test field 
      operationId: errorcheck
      parameters:
        - name: param1
          in: body
          description: description
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Successs
          schema:
            type: string
        default:
          description: Error
          schema: 
            $ref: "#/definitions/ErrorResponse" 
        
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  foo:
    required:
      - foo
    properties:
      foo:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
```

My curl command: `curl -X POST -H "Content-Type: application/json" -d 'test' http://localhost:3000/v1/errorcheck` 

Response from curl: 
```
Error: invalid json<br> &nbsp; &nbsp;at parse (/Users/plingampally/Documents/XXXX/YYYY/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/body-parser/lib/types/json.js:79:15)<br> &nbsp; &nbsp;at /Users/plingampally/Documents/XXXX/YYYY/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/body-parser/lib/read.js:102:18<br> &nbsp; &nbsp;at done (/Users/plingampally/Documents/XXXX/YYYY/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/body-parser/node_modules/raw-body/index.js:248:14)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/Users/plingampally/Documents/XXXX/YYYY/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/body-parser/node_modules/raw-body/index.js:294:7)<br> &nbsp; &nbsp;at IncomingMessage.g (events.js:199:16)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:104:17)<br> &nbsp; &nbsp;at _stream_readable.js:908:16<br> &nbsp; &nbsp;at process._tickCallback (node.js:355:11)
```

**Comment by prabhatjha** [comment]
Hmm I don't see /errorcheck path defined in your swagger. May be you
copy/pasted wrong file. I only see /hello, /listtestfields, /trustedfields
. For examples, you can see it at
https://github.com/swagger-api/swagger-editor/blob/master/app/spec-files/petstore_full.yaml

On Thu, Jun 11, 2015 at 2:12 PM, Pari Lingampally <notifications@github.com>
wrote:

> Hi @prabhatjha <https://github.com/prabhatjha> the link you posted did
> not have a post example, it only had one get request.
>
> here is my full swagger:
>
> swagger: "2.0"info:
>   version: "0.0.1"
>   title: Hello World App# during dev, should point to your local machinehost: localhost:3000# basePath prefixes all resource paths basePath: /v1# schemes:
>   # tip: remove http to make production-grade
>   - http
>   - https# format of bodies a client can send (Content-Type)consumes:
>   - application/json# format of the responses to the client (Accepts)produces:
>   - application/jsonpaths:
>   /hello:
>     # binds a127 app logic to a route
>     x-swagger-router-controller: hello_world
>     get:
>       description: Returns 'Hello' to the caller
>       # used as the method name of the controller
>       operationId: hello
>       parameters:
>         - name: name
>           in: query
>           description: The name of the person to whom to say hello
>           required: false
>           type: string
>       responses:
>         200:
>           description: Success
>           schema:
>             # a pointer to a definition
>             $ref: "#/definitions/HelloWorldResponse"
>         # responses may fall through to errors
>         default:
>           description: Error
>           schema:
>             $ref: "#/definitions/ErrorResponse"
>   /listtestfields:
>     x-swagger-router-controller: metadata
>     get:
>       description: Returns all the test fields
>       operationId: listTestFields
>       responses:
>         200:
>           description: Success
>           schema:
>             type: array
>             items:
>               $ref: "#/definitions/foo"
>         default:
>           description: Error
>           schema:
>             $ref: "#/definitions/ErrorResponse"
>   /trustedfields:
>     x-swagger-router-controller: metadata
>     get:
>       description: Returns the trusted fields for a given test field
>       operationId: trustedFields
>       parameters:
>         - name: testfield
>           in: query
>           description: Field to be tested against
>           required: true
>           type: string
>       responses:
>         "200":
>           description: Successs
>           schema:
>             type: array
>             items:
>               $ref: "#/definitions/foo"
>         "400":
>           description: Invalid Test Field
>           schema:
>             $ref: "#/definitions/ErrorResponse"
>
>         default:
>           description: Error
>           schema:
>             $ref: "#/definitions/ErrorResponse"
>   /errorcheck:
>     x-swagger-router-controller: errorcheck
>     post:
>       description: Runs an error check against a given test field
>       operationId: errorcheck
>       parameters:
>         - name: param1
>           in: body
>           description: description
>           required: false
>           schema:
>             type: string
>       responses:
>         "200":
>           description: Successs
>           schema:
>             type: string
>         default:
>           description: Error
>           schema:
>             $ref: "#/definitions/ErrorResponse"
> # complex objects have schema definitionsdefinitions:
>   HelloWorldResponse:
>     required:
>       - message
>     properties:
>       message:
>         type: string
>   foo:
>     required:
>       - foo
>     properties:
>       foo:
>         type: string
>   ErrorResponse:
>     required:
>       - message
>     properties:
>       message:
>         type: string
>
> My curl command: curl -X POST -H "Content-Type: application/json" -d
> 'test' http://localhost:3000/v1/errorcheck
>
> Response from curl:
>
> Error: invalid json<br> &nbsp; &nbsp;at parse (/Users/plingampally/Documents/XXXX/YYYY/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/body-parser/lib/types/json.js:79:15)<br> &nbsp; &nbsp;at /Users/plingampally/Documents/XXXX/YYYY/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/body-parser/lib/read.js:102:18<br> &nbsp; &nbsp;at done (/Users/plingampally/Documents/XXXX/YYYY/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/body-parser/node_modules/raw-body/index.js:248:14)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/Users/plingampally/Documents/XXXX/YYYY/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/body-parser/node_modules/raw-body/index.js:294:7)<br> &nbsp; &nbsp;at Inco
>  mingMess
>  age.g (events.js:199:16)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:104:17)<br> &nbsp; &nbsp;at _stream_readable.js:908:16<br> &nbsp; &nbsp;at process._tickCallback (node.js:355:11)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swagger-api/swagger-node/issues/218#issuecomment-111278812>
> .
>



-- 
Cheers,
Prabhat
---------------------------
Help spread www.eejot.org

**Comment by plingampally** [comment]
Maybe I am confused, but I have included the /errorcheck path in the above swagger file. I have pasted it here as well . 

```yaml
  /errorcheck:
    x-swagger-router-controller: errorcheck
    post:
      description: Runs an error check against a given test field 
      operationId: errorcheck
      parameters:
        - name: param1
          in: body
          description: description
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Successs
          schema:
            type: string
        default:
          description: Error
          schema: 
            $ref: "#/definitions/ErrorResponse" 
```

**Comment by prabhatjha** [comment]
My bad..Instead of opening thread here, I had in my mail client which stripped part of swagger. Let me try on my side.

**Comment by prabhatjha** [comment]
Just tried. In your curl, curl -X POST -H "Content-Type: application/json" -d 'test' http://localhost:3000/v1/errorcheck , your json payload is 'test' which is not a valid json. If you use following curl, curl -X POST -H "Content-Type: application/json" -d '{"name":"blah"}'  http://127.0.0.1:10010/errorcheck , you should see that your request made it through.

**Comment by plingampally** [comment]
@prabhatjha thanks for the help! I was finally able to get my responses to validate by setting my schema like this: 

```yaml
responses:
        "200":
          description: Successs
          schema:
            type: object
``` 

For some reason, I was not able to get the other schema types to work. Thanks again!
