### ISSUE TITLE
Swagger-node seems more strict than petstore.swagger.io would imply

### ISSUE THREAD

**Issue by nikdunn** [swagger-api/swagger-node#223]
In the petstore.swagger.io example application, certain APIs like DELETE /pet/{petId} do not define default response codes or handle response code 200, but they still work.

In my swagger-node application, the server blows up with TypeError: Cannot read property 'type' of undefined at Object.isModelParameter in helpers.js around line 55.

The code is trying to find a schema for the response code, but since one wasn't added to the spec and neither was a default, it blows chunks.

Should the swagger-node implementation handle this more gracefully like the petstore.swagger.io sample application?

**Comment by nikdunn** [comment]
After talking with some of the folks that know the back end of the pet store application, I learned that it uses java as the back end. The java implementation of swagger only generates the API it does not validate against it. So the petstore.swagger.io json is not valid, but I have no issue with swagger-node's validation.

**Comment by webron** [comment]
To be clear, the pet store's Swagger definition is valid.
