### ISSUE TITLE
Please add example how to implement security handler

### ISSUE THREAD

**Issue by surmanajaja** [swagger-api/swagger-node#228]
Hi

This is quite newbie issue. there must be better place to aske this but I can't find. I hope someone either helps me with this by adding some documentation or points me to proper place.
I try to add my own security handler. I created default swagger project, and tested it, fine. then edit swagger file,
```yaml
securityDefinitions:
  mySecKey:
    type: apiKey
    in: query
    name: sec_key
```
and
to paths; /hello: get: I added:
```yaml 
      security:
        - mySecKey: []
```
now running
swagger project test 
gives me "Error: unknown security handler: mySecKey"
how to implement that without complately rewrite app.js as all examples shows.

**Comment by theganyo** [comment]
This feature is not yet officially supported in swagger-node, but if you need to, you can get access to swagger-tools and register a security handler with it. See: https://github.com/apigee-127/swagger-tools/blob/master/docs/Middleware.md#swagger-security for information. Your app.js will look something like this:

````
SwaggerExpress.create(config, function(err, swaggerExpress) {
  if (err) { throw err; }

  // install middleware
  swaggerExpress.register(app);

  var options = { mySecKey:
    function (req, authOrSecDef, scopesOrApiKey, callback) {
      ...
    }
  };
  swaggerExpress.runner.swaggerTools.swaggerSecurity(options);

  var port = process.env.PORT || 10010;
  app.listen(port);

  console.log('try this:\ncurl http://127.0.0.1:' + port + '/hello?name=Scott');
});
````

This should work, just be aware that swagger-tools is an implementation detail / private API and will not remain under the covers forever.

Scott

**Comment by sohn** [comment]
The code above didn’t work for me. I was able to get it to recognize the security handler by calling the following within the SwaggerExpress callback, before swaggerExpress.register()

```javascript
swaggerExpress.runner.config.swagger.securityHandlers = { 
    mySecKey: function (req, authOrSecDef, scopesOrApiKey, callback) {
        // ...
    }
}

// install middleware
swaggerExpress.register(app);
```

**Comment by theganyo** [comment]
Great! Glad you got it working! Same caveats as above apply. :)

**Comment by surmanajaja** [comment]
thx, solution sohn pointed works.

**Comment by danielmihai** [comment]
How do i use passport js with SwaggerExpress, redis and express-session ? 
Please, help!

**Comment by rajeevb2** [comment]
I got the @sohn solution to work but it is messy. When will a cleaner version be available -- maybe using  a x-swagger-security-handler tag?

**Comment by theganyo** [comment]
The new version supports passing in a security handler directly in the config. See: https://github.com/swagger-api/swagger-node/blob/master/docs/release-notes.md

**Comment by rajeevb2** [comment]
@theganyo: with swagger+sails where do I add the security handler?

**Comment by theganyo** [comment]
@rajeevb2 Oh boy. Sails is a challenge. The only way currently would be to literally edit the plugin. As a Salis user, what would you expect? Maybe we can try to work from there.

**Comment by rajeevb2** [comment]
@theganyo I got it to work but as you indicated, I had to edit the plugin. Ideally, I would like this to work as a sails policy.

**Comment by chrisfelix82** [comment]
I want to gain access to the res and next handler to properly return 401 or 403 errors.  I added the following to app.js:

    swaggerExpress.runner.config.swagger.securityHandlers = {
    oAuth: function (req, res, next,authOrSecDef, scopesOrApiKey) {
        //res.sendStatus(403);
        next();
    }
  }

This works if I drill down and change node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/middleware/swagger-security.js and change line 149 to :
  handler(req,res,next,secDef, getScopeOrAPIKey(req, secDef, name, secReq));

What do you think about giving us access to the req,res and next object so that we can properly short circuit and return 401 or 403?  Thanks.

**Comment by chrisfelix82** [comment]
OK my bad.  dug a little more.  Looks like I can get what I need by passing this to the callback.

cb({message: "Error doing something",
            code: "SomeAppCode",
            statusCode: 401,
            headers: []
          });

or cb(); for success

**Comment by jeonghwan-kim** [comment]
This is my code is working.

app.js:

```javascript
var config = {
  appRoot: __dirname, // required config
  swaggerSecurityHandlers: {
    api_key: function (req, authOrSecDef, scopesOrApiKey, cb) {
      // your security code
      if ('1234' === scopesOrApiKey) {
        cb(true);
      } else {
        cb(new Error('access denied!'));
      }
    }
  }
};
```

api/swagger/swagger.yaml:

```yaml
securityDefinitions:
  api_key:
    type: apiKey
    in: query
    name: api_key
paths:
  /hello:
    get:
      security:
        - api_key: [ ]
```

**Comment by rajeevb2** [comment]
I am still interested in a way to specify this inside swagger-sails (as a policy inside config/).

Anyone got this to work?

Rajeev

**Comment by sah2ed** [comment]
@jeonghwan-kim kudos for the snippet except that there is a tiny bug in the code you posted which causes it to fail with `Cannot assign to read only property 'code' of true`.

Had to change `cb(true);` to `cb(null);` to get it working in swagger-express-mw v0.6.0.

```js
var config = {
  appRoot: __dirname, // required config
  swaggerSecurityHandlers: {
    api_key: function (req, authOrSecDef, scopesOrApiKey, cb) {
      // your security code
      if ('1234' === scopesOrApiKey) {
        cb(null);
      } else {
        cb(new Error('access denied!'));
      }
    }
  }
};
```

**Comment by evilive3000** [comment]
well, I did explore `swagger_security` fitting and figure out a few options how to activate handlers:

at first you have to define a security module:
```javascript
// api/helpers/security_module.js

module.exports = {
  // swagger-tools style handler
  security_1: function failure(req, authOrSecDef, scopesOrApiKey, next) {
   /* security checking logic */
  }

  // connect-style handler
  security_2: function failure(req, res, next) { 
   /* security checking logic */
  }
};
```
Now you have 2 options:

I). You can include it in you `app.js` as mentioned before:
```javascript
// swaggerSecurityHandlers

const config = {
  appRoot: __dirname, // required config

  // both keys are correct, pick one you likes more ^_^
  securityHandlers: require('./api/helpers/security_module'),
  // or
  swaggerSecurityHandlers: require('./api/helpers/security_module')
};
```

II). Or you can modify `config/default.yaml`
 1. add `_swagger_security` definition:
```yaml
    _swagger_security:
      name: swagger_security
      securityHandlersModule: api/helpers/security_module
```
 2. and replace `swagger_security` to `_swagger_security`
```yaml
    # pipe for all swagger-node controllers
    swagger_controllers:
      - onError: json_error_handler
      - auth_mw
      - cors
      - swagger_params_parser
      - _swagger_security
      - _swagger_validate
      - express_compatibility
      - _router
```

But I did not get a [line](https://github.com/theganyo/swagger-node-runner/blob/master/fittings/swagger_security.js#L15):
```javascript 
if (fittingDef.securityHandlersModule && !runner.config.securityHandlers)
```
I found an [issue](https://github.com/theganyo/swagger-node-runner/issues/70#issuecomment-259215524) where @osher asked the same question. Can somebody show the reason that checking exists?

**Comment by japalo** [comment]
To further explain, here is my config object:
```javascript
var config = {
    appRoot: __dirname, // required config
    swaggerSecurityHandlers: {
        OauthSecurity: function(req, authOrSecDef, scopesOrApiKey, callback) {
            callback.apply(); // Does not return my mock controller
        }
    }
};
```

**Comment by japalo** [comment]
Never mind, it was me who made an error in my mock controller.

**Comment by jeshan** [comment]
Here is a working example. This is what worked for me:
```
let swaggerConfig = {
  appRoot: __dirname, // required config
  swaggerSecurityHandlers: {
    BasicAuth: function (req, res, next) {
      log.info('auth:' + req.headers.authorization);
      let prefix = 'Basic ';
      if (req.headers.authorization && req.headers.authorization.startsWith(prefix)) {
        let value = req.headers.authorization.substr(prefix.length);
      }
      // put your validation somewhere here
      // 403 is the default error code, feel free to override with, e.g 401
      next({code: 'Custom_application_error_code', statusCode: 401});
    }
  }
};
```

What I had in my default yaml (order may be significant):
```
    swagger_controllers:
      - onError: json_error_handler
      - cors
      - swagger_params_parser
      - swagger_security
      - _swagger_validate
      - express_compatibility
      - _router

```

In my swagger definition:

```
securityDefinitions:
  BasicAuth:
    type: basic
security:
-  BasicAuth: []
```
Tested with swagger-express-mw 0.7.0

**Comment by wraytw** [comment]
I have the exact same setup as above, except with the apiKey auth type. It works great!

**Comment by osher** [comment]
I think we need to move all these insights to the wiki

**Comment by b4dnewz** [comment]
Global security definitions are not working with "swagger-express-mw": "^0.7.0"

```
TypeError: Cannot read property 'type' of undefined
  at getScopeOrAPIKey (/usr/src/app/node_modules/swagger-express-mw/node_modules/swagger-node-runner/fittings/swagger_security.js:80:26)
```

**Comment by evilive3000** [comment]
@b4dnewz , provide more code, show your swagger definition file and and security handlers.

**Comment by b4dnewz** [comment]
This piece of code should add the global security definition to all paths. @evilive3000 
```yml
security:
 - Bearer: []
securityDefinitions:
  Bearer:
    type: apiKey
    in: header
    name: Authorization
```
But when the security handler is called it fails with the error posted above, see [this discussion](https://github.com/apigee-127/sway/pull/145).

**Comment by evilive3000** [comment]
yeap, unfortunately it is nothing we can do until @whitlockjc update sway on npmjs. 
But the package was not updated since 2016.

**Comment by uniquejava** [comment]
> OK my bad. dug a little more. Looks like I can get what I need by passing this to the callback.
> 
> cb({message: "Error doing something",
> code: "SomeAppCode",
> statusCode: 401,
> headers: []
> });
> 
> or cb(); for success

@chrisfelix82  👍  NICE!, I want to customize status code from 403 to 401.  Don't know where to do this and finally Googled here !!!! This saves me! Thank you.
