### ISSUE TITLE
swagger-node-express's github now 301 redirects to here (swagger-api/swagger-node).

### ISSUE THREAD

**Issue by Riobe** [swagger-api/swagger-node#230]
I'd create this as an issue on that repo, but I can't get to it and they were both belonging to swagger-api, so hopefully this is the right place to post this issue. The git repository link on the npm page for [swagger-node-express](https://www.npmjs.com/package/swagger-node-express) does a 301 permanent redirect to this repository.

We are using swagger-node-express at work and seeing the repository disappear for it is disconcerting at best. Can we know what happened? Perhaps the repository can be put back? My understanding is that if the repository is now deprecated that [npm deprecate](https://docs.npmjs.com/cli/deprecate) is the right way to go about it.

**Comment by fehguy** [comment]
Hi, the repository has been renamed and undergone a major revision.  You can still reach the old project under the 2.0.x tag

**Comment by Riobe** [comment]
Can the original repository be put back? Maybe you didn't like it, but you had published an npm package using that repo and for it to disappear like that after people were relying on it is incredibly frustrating. I lost a lot of hours due to that.

If you don't want to support it anymore deprecate it or something, but simply removing the repository and now only having the code as a tag in a repository for another project is not the right way. We've now stopped using any swagger-api repositories at my job.

**Comment by fehguy** [comment]
Hi, I'm sorry @Riobe.  We do have the repository still here, and every published code branch is in the tags area.  The most recent is here:

https://github.com/swagger-api/swagger-node/tree/v2.1.2

It is the same code repo, just renamed to something more intuitive.  Please comment here if you have more questions on this, I'd like to make the transition as easy as possible.

**Comment by Riobe** [comment]
Having the repo renamed is the same thing as removing the old repo and making a new one. The fact that it is in the tags does not change the fact that the link https://github.com/swagger-api/swagger-node-express , which is linked to by https://www.npmjs.com/package/swagger-node-express no longer exists and should. You published something and people (at least my team) started relying on it and then it got removed.

The fact that the code is still hidden down in a commit tagged in a different repo does not make things better. I would have expected that if you wanted to make a differently named project, that would be a new repo. This is the first time I've seen an open source repo that was being used and had code published just get renamed and repurposed. Until that previous repository exists again I don't feel comfortable relying on any swagger-api projects when they can just be renamed, re-purposed, and effectively removed after I've used them in prod.

In the end, it's your projects and your control so do what you feel is best, obviously. You can close the issue if you want. I wish you the best with your work.

**Comment by webron** [comment]
Sorry to hear you feel that way, but nothing has been removed, and nothing is lost. Some of it is how git works in general, and some how github works specifically. Versions are tagged, and no code is lost. It remains there. The renaming expresses the purpose of the new code. The redirect is just how Github functions. All directions to the old name would be redirected to the new one, and Github does that automatically. So you won't get a 404 on that. Projects advance and evolve, and yes, some links may go stale. 

We *could* recreate the swagger-node-express project and add a README that points people to the specific last tag in *this* repository. I'm not sure there's real benefit here. We won't copy the code to that repository though as that doesn't make sense maintenance-wise. The project is not longer maintained, and new version replaces it. This is our vision on how we choose to improve the projects. The spec evolves too and is not 100% backwards compatible. Such is the life of software.

If you feel we could/should have made the process better, we do appreciate the feedback and hope to improve the process better. However, from that to the statement you've made it's a long way. We're not doing anything to harm anyone. On the contrary, we thrive to improve and provide better quality of work all the time. However, if you choose to not rely on our projects, as much as it saddens us, we'd respect your choice.

**Comment by LeviRosol** [comment]
FWIW, I just spent an hour tracking down this info.

Further adding to the confusion `npm info swagger-node-express` returns a home page of `https://github.com/swagger-api/swagger-node-express` that does the 301 mentioned, and the readme for the new project doesn't provide any info on the old project or where to find it.

Also of note, the version returned in `npm info` shows a version of 2.1.3, but the last tag / package.json shows the old project is at 2.1.2. That leads me to assume I'm not actually on the correct repo yet.

**Comment by fehguy** [comment]
Sorry @LeviRosol.  As noted before, we made some mistakes when making substantial upgrades to this project.  It _was_ called swagger-node-express but the project was renamed to swagger-node, and completely rebuilt.

In hindsight, we should have kept the old repo around and made this a new one.  I'll take the blame (but it wasn't my choice).

**Comment by LeviRosol** [comment]
No worries. It's all in the name of progress right?  :)

This may not be the ideal place to ask this question, so I'll keep as brief as I can. We've used this module in other projects, and prefer to document as we code vs using the generator that the master branch seems to promote.

Starting a new project, we of course used bits of older projects to get off the ground, including swagger-node-express and its `spec` in the route code pattern. My question is, what is the suggested pattern for using the new module within a project? Are there any blog posts on this topic that my google-fu doesn't seem to be finding?

I do dig the idea of self contained swagger documentation outside of actual code (what I'm inferring the new project promotes), however, since we not only use the swagger spec for swagger, but also for end point documentation in the code, we prefer to keep them together.

**Comment by tncbbthositg** [comment]
@fehguy, thanks for the history on the two projects.  

I'm looking for documentation on using the new project for code-first API development.  We'd primarily like to use the package to generate our swagger docs from our api code like the previous package provided.

Has anybody come across these docs yet?

Thanks!!
