### ISSUE TITLE
Does Swagger Node only produce raw doc endpoints? Does it generate a UI endpoint as well?

### ISSUE THREAD

**Issue by behrangsa** [swagger-api/swagger-node#234]
Hi,

Does Swagger Node produce a URL such as `/swagger/ui/index.html` to serve the HTML human readable documentation?

Or do we have to manually install swagger-ui and configure it?

**Comment by theganyo** [comment]
We do intend to support this, but unfortunately you'll have to install and configure it manually for now.

**Comment by mohsen1** [comment]
You can look at [this file](https://github.com/noahdietz/swagger-travel-groups/blob/master/travel-groups/swagger-ui-router.js) as a sample of doing it manually.

**Comment by behrangsa** [comment]
@theganyo no worries. Looking forward to it :smiley: 

@mohsen1 I just installed swagger-ui and configured my Express app to serve it via static middleware. But ideally I was looking for it to be configured automatically.

**Comment by theganyo** [comment]
Closing as duplicate of #4.
