### ISSUE TITLE
It would be nicer if the swagger middleware for Express could be installed like other middleware

### ISSUE THREAD

**Issue by behrangsa** [swagger-api/swagger-node#235]
Hi,

It would be nicer if the Swagger middleware for Express could be installed like other Express middleware. For example like this:

```javascript
app.use(swagger.express({
	appRoot: __dirname
}));

// or

app.use(swaggerExpress.config({
	appRoot: __dirname
}));
```

rather than:

```javascript
SwaggerExpress.create(config, function(err, swaggerExpress) {
    if (err) { throw err; }

    swaggerExpress.register(app);

    var port = 10101;
    app.listen(port);
});
```

**Comment by theganyo** [comment]
Yes, it would be, but the loading of the swagger (via swagger-tools for now) is async and starting with just a .use would cause the server to start in an uninitialize and potentially bad state. I'm open to suggestions, but it would need a compelling and complete solution to be changed.

**Comment by mohsen1** [comment]
Loading a swagger spec can not be sync since it might involve loading referenced dependencies from net. If you have a swagger that has no reference to external files it can be sync but then we need two different APIs which I don't think it helps making the API "simpler".

We can change the API for `   swaggerExpress.register(app);` line to `app.use` syntax.

**Comment by theganyo** [comment]
@mohsen1 No, there is good reason to leave this line as it is. The framework does more than just register a middleware.

**Comment by behrangsa** [comment]
@theganyo I will have a look at the code in my spare time and see if I can do something about it. In the meantime I think we can close this issue and reopen it later.

---

P.S: In other platforms (Java, .NET), using Swagger is orthogonal to the rest of the framework. Controllers and controller actions usually don't even know it exists. They might get annotated here and there, but other than that, with or without swagger, they can be used without any code changes.

However with `swagger-node`, the parsed parameters are set on `req.swagger.params.foo.value`. If we decided to stop using swagger we have to change all these lines of code. Wouldn't it be nicer if swagger had replaced `req.params.foo` with the parsed value so that our actions could work independently of swagger?

**Comment by theganyo** [comment]
I think that it's a valid discussion point on why the parameter values are handled so differently from express-based applications. Obviously, to be able to deliver not only the value, but all the swagger metadata, having a system other than req.params is required. But, I'm not sure if there's a reason why the actual values are not also populated there as one would expect in express... So, I'll tag the author of swagger-tools (@whitlockjc) to join us here and provide any input he has. If there is no strong reason not to, we should certainly consider a configurable option to set the swagger-derived values to req.params.

**Comment by theganyo** [comment]
I'm closing this for now. Hopefully we can still get a comment from @whitlockjc addressing the parameters question, though.
