### ISSUE TITLE
What's the difference between swagger project start and running the app just by using `node app`?

### ISSUE THREAD

**Issue by behrangsa** [swagger-api/swagger-node#236]
How does `swagger project start` differ from `node app`?

_PS: Is there a mailing list available for swagger-node? Or should we continue asking questions here?_

**Comment by theganyo** [comment]
Right now it offers the following for development convenience:
* executes using nodemon, so it restarts on changes to the yaml, js, or json files (also coffee, fwiw)
* enables CORS so the swagger editor's "try it" functionality will work
* optionally enables mocking for the controllers

**Comment by behrangsa** [comment]
@theganyo Thanks for clarification. So for prod we probably should just use `node app`?

_PS: Is it okay if we continue asking suchlike questions here? :smiley:_

**Comment by theganyo** [comment]
I think that planning on using "node app" is fine for the foreseeable future.

And, yes, asking question here is completely valid. :)
