### ISSUE TITLE
Add support for XML response

### ISSUE THREAD

**Issue by npedrini** [swagger-api/swagger-node#256]
It would be great if support for XML output could be added, and ideally, validation against response schemas.

Currently, the following try/catch block on line 101 of swagger-tools/swagger-validator.js generates the `Value expected to be an array/object but is not` error:

    if (_.isString(val)) {
      try {
        val = JSON.parse(val);
      } catch (err) {
        err.failedValidation = true;
        err.message = 'Value expected to be an array/object but is not';
        throw err;
      }
    }

Implementation would ideally perform the same check for valid XML conforming to the schema, but  bypassing this block does output the XML response.

**Comment by theganyo** [comment]
It sounds like this is a swagger-tools issue?

**Comment by jeffswitzer** [comment]
I'm also running into this issue. Express seems to be returning valid xml, but swagger complains with error @npedrini specified

**Comment by MobileAppVault** [comment]
Is there any fix for that? Same issue with express and swagger. Not able to return XML format. :(
