### ISSUE TITLE
Trying to use swagger node on an existing project

### ISSUE THREAD

**Issue by RaviVaranasi** [swagger-api/swagger-node#257]
Running `swagger project open` seems to be looking api/swagger/swagger.yaml. I have it under vendor/api/swagger/swagger.yaml.

1. Is it possible to use swagger-node-express with an existing project structure ?

* How can we override this to account for my directory structure?
* Does it generate the usage pageby default or does it need some special configuration with swagger-ui ?

Thanks,
Ravi

**Comment by theganyo** [comment]
Unfortunately, different project structures aren't well supported at present. This functionality was intended and much of the code is localized, but I've identified some bugs that will prevent it from working well for you.

You'll need to do your own swagger-ui work for now.

**Comment by sudeepdk** [comment]
thanks @theganyo
