### ISSUE TITLE
No schema support for responses using res.write with express?

### ISSUE THREAD

**Issue by kraf** [swagger-api/swagger-node#263]
For one API call I'm pulling a lot of data from a database and to avoid having to allocate everything in memory while I prepare the response I convert the rows to JSON on the fly and send them with `res.write` immediately.

My (obfuscated) path definition:

``` yaml
/my/path:
  x-swagger-router-controller: myController
  get:
    summary: Returns some data
    description: Returns some data
    operationId: someOperationId
    tags:
      - someTag
    responses:
      "200":
        description: Success
        schema:
          $ref: "#/definitions/ObjectArray"
      default:
        description: Error
        schema:
          $ref: "#/definitions/ErrorResponse"
```

The problem is that swagger doesn't seem to be picking up the schema of the response, it thinks it's `undefined` and validation fails. When I take out the schema for the response everything works fine.
I realize that swagger would have to actually assemble the entire response in memory for schema validation to work which would defeat the purpose of what I'm doing here. I would still like to be able to provide documentation for the API response if this is possible. Can I provide a schema while disabling validation for this one call or indicate that the response will be a stream?

I'm doing something like this:

``` javascript
res.status(200).set('Content-Type', 'application/json');
res.write('[');
res.write('{"id":"1", ...},');
res.write('{"id":"2", ...}');
res.write(']');
res.end() // => swagger alerts me about validation error here
```

**Comment by whitlockjc** [comment]
Can you run swagger-node via `DEBUG=swagger-tools*` and let us see the related part about the response validation failure?  When we do response validation, we do it pretty much like request validation:

* Make sure the `Content-Type` is allowable
* Make sure the response passes JSON Schema validation *(If we cannot find a response schema, we actually skip this part)*

Debugging as mentioned above will help a lot.

**Comment by kraf** [comment]
I'm afraid the debug output doesn't help:

```
swagger-tools:middleware:metadata GET /hello?name=Scott +2s
swagger-tools:middleware:metadata   Is a Swagger path: true +0ms
swagger-tools:middleware:metadata   Is a Swagger operation: true +0ms
swagger-tools:middleware:metadata   Processing Parameters +0ms
swagger-tools:middleware:metadata     name +1ms
swagger-tools:middleware:metadata       Type: string +0ms
swagger-tools:middleware:metadata       Value provided: true +0ms
swagger-tools:middleware:metadata       Value: Scott +0ms
swagger-tools:middleware:security GET /hello?name=Scott +0ms
swagger-tools:middleware:security   Will process: yes +0ms
swagger-tools:middleware:validator GET /hello?name=Scott +0ms
swagger-tools:middleware:validator   Will process: yes +0ms
swagger-tools:middleware:router GET /hello?name=Scott +1ms
swagger-tools:middleware:router   Will process: yes +0ms
swagger-tools:middleware:router   Route handler: hello_world_hello +0ms
swagger-tools:middleware:router   Mock mode: false +1ms
Error: Response validation failed: failed schema validation
    at throwErrorWithCode (.../hello-world/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/lib/validators.js:97:13)
    at Object.validateAgainstSchema (.../hello-world/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/lib/validators.js:126:7)
    at .../hello-world/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/middleware/swagger-validator.js:119:22
    at .../hello-world/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/async/lib/async.js:246:17
    at .../hello-world/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/async/lib/async.js:122:13
    at _each (.../hello-world/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/async/lib/async.js:46:13)
    at async.each (.../hello-world/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/async/lib/async.js:121:9)
    at _asyncMap (.../hello-world/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/async/lib/async.js:245:13)
    at Object.map (.../hello-world/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/async/lib/async.js:216:23)
    at validateValue (.../hello-world/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/middleware/swagger-validator.js:112:11)
```

I might not have been entirely clear about the issue. The validation works fine, but it's validating against the value `undefined`, because I am building the response string myself and streaming it and the middleware seems to only hook into `res.send` and `res.json` but not `res.write`. So this works:
```
res.json({message: "hello"});
```
but this does not
```
res.write('{"message": "hello"}');
res.end();
```
To get above error I used the auto-generated code from `swagger project create hello-world` with the express module. I had to add `type: object` explicitly to the HelloWorldResponse for it to do the validation (which I don't entirely understand) and then tested with both versions from above.

**Comment by dcolens** [comment]
Is it possible to disable the response validation ?

**Comment by connesc** [comment]
@fehguy, why has this been closed ?
That fact that response validation is not aware of [`res.write`](https://nodejs.org/api/http.html#http_response_write_chunk_encoding_callback) looks like a major issue.
At least, it might be mentioned somewhere.
