### ISSUE TITLE
How can we use Express with Swagger after the changes in the new version of swagger-tools?

### ISSUE THREAD

**Issue by behrangsa** [swagger-api/swagger-node#268]
See: https://github.com/apigee-127/swagger-tools/issues/259

How can we map an operationId to an action method that happens to have the same name as another action method in another controller?

**Comment by whitlockjc** [comment]
My plan is to revert the change in swagger-tools, release `0.9.2` and resurrect the change when `1.0.0` is released.

**Comment by theganyo** [comment]
I believe this has been addressed for now.
