### ISSUE TITLE
Run project forever

### ISSUE THREAD

**Issue by diaspar** [swagger-api/swagger-node#276]
How do you do to have the project available forever?

I have my docs using the express version. Locally I run:

swagger project start

But I am not sure how to do it on a public server. I tried installing the npm module forever but this does not work: 

forever swagger project start

Any ideas?

**Comment by theganyo** [comment]
You can run your project directly using "npm start" or even "node app.js".

**Comment by diaspar** [comment]
thanks.

The final command I used was: forever start app.js

This thread also gave me some ideas of the trade-offs about using the app.js directly:

https://github.com/swagger-api/swagger-node/issues/236#issuecomment-115748132
