### ISSUE TITLE
running swagger-ui and api in single process

### ISSUE THREAD

**Issue by devzer01** [swagger-api/swagger-node#281]
Hi, 

i was wondering if there was any quick builtin method to run both the swagger-ui and the actual API using the same process and essentially using the same IP:PORT 

all our php based swagger defined API behaves this way, so that developers can reach the API URL and interact with the API.

**Comment by theganyo** [comment]
Here is one method: https://github.com/noahdietz/swagger-travel-groups/blob/master/travel-groups/swagger-ui-router.js

**Comment by devzer01** [comment]
Thank you. Will try it out.

Sent via mobie
