### ISSUE TITLE
Swagger Validation for File Downloads: schema type: file is shown as response validation error

### ISSUE THREAD

**Issue by Srithar-ccs** [swagger-api/swagger-node#283]
Swagger Validation failed for ZIP File Download,

I am trying to write a file download API. It is a stream type for response but it is failing as "Response Validation failed"

My Yaml FIles is like this:
```
produces:
  - application/zip

/library/getacitemspackage:
  # This is the controller for getting the acitem and all its internal references as a deep package for the seamless delivery
    x-swagger-router-controller: library_get_acitems_package
    # this is a post method verb of the api service call
    post:
      summary: The API does the zip of all the given acitems and brings all the deep copy references packages from the cloud library
      description: The API does the zip of all the given acitems and brings all the deep copy references packages from the cloud library
      operationId: libraryGetAcitemsPackage
      parameters:
        - name: acitemsList
          in: body
          description: The list of all the acitems for which the package needs to be delivered as a zip
          schema:
            type: object
      responses:
        "200":
          description: Success
          schema:            
            type: file
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
```
My API code is like this :
```
            var archive = archiver('zip');          
            var totalAcitemListArray = totalAcitemList.toArray();           
            for (var index = 0; index < totalAcitemListArray.length; index++) {
                archive.append(fs.createReadStream(path.join(root_directory, totalAcitemListArray[index])), { name:totalAcitemListArray[index] });
            }           
            archive.finalize();
            archive.on('error', function(err) {
                response.status(500).send({error: err.message});
            });
            response.send('acitemsPackage.zip');            
            archive.pipe(response);
```

Also i have had a chat with @webron regarding this issue. I am raising this ticket as a follow up for the revision of the swagger-tools in the swagger-node project for file send utilities.
https://github.com/swagger-api/swagger-spec/issues/446

**Comment by webron** [comment]
This is most likely just a matter of updating swagger-tools to the latest version (issue should be fixed in 0.9.1).

**Comment by theganyo** [comment]
Great! Swagger-node will already use the latest version of swagger-tools (0.9.2). Just use `npm update` or delete your `node_modules` directory and reinstall your dependencies with `npm install`.

**Comment by webron** [comment]
Thanks @theganyo  - since I'm still very very new to node development, wouldn't https://github.com/swagger-api/swagger-node/blob/master/package.json#L35 suggest otherwise? If not, would be a good time for me to learn :)

**Comment by theganyo** [comment]
You bet. :) So all versions in NPM use [semver](https://www.npmjs.com/package/semver) for resolution. Thus, this line:

`"swagger-tools": "^0.9.0"`

is what semver calls a [carrot range](https://www.npmjs.com/package/semver#caret-ranges-1-2-3-0-2-5-0-0-4), which states that it "allows changes that do not modify the left-most non-zero digit". Meaning, it will resolve the above version as a range matching this:

`"swagger-tools": "0.9.x"`

There can be a lot of complexity in version ranges in semver, but the carrot range is the default when you use `npm install --save` and seems to be a decent option to live by for the most part.

I hope that helps!

**Comment by webron** [comment]
Awesome, thanks for the explanation!

**Comment by Srithar-ccs** [comment]
Hi great folks, I updated my npm package as you mentioned in the above thread and my project is now working like a charm. Thanks a lot for the great help. this means a lot to me. I shall close the issue now. Once again thank you. Appreciate your great contribution :)
