### ISSUE TITLE
Cannot use arrow keys select framework on Windows 10

### ISSUE THREAD

**Issue by zhouqianli** [swagger-api/swagger-node#286]
Cannot use arrow key select framework when follow the [quick start guide](https://github.com/swagger-api/swagger-node/blob/master/docs/quick-start.md#get-an-api-up-and-running) on **Windows 10**.  A workaround is using ` swagger project create -f express hello-world `.

**Comment by vincpa** [comment]
I have this same issue both in CMD and PowerShell.

**Comment by mohsen1** [comment]
Sounds like a [commander](https://github.com/tj/commander) bug, can you make a simple commander app and try it out?

**Comment by theganyo** [comment]
Actually, [inquirer](https://github.com/sboudrias/Inquirer.js), not commander. The version of inquirer was updated in the new beta for swagger-node. Can you give it a try and let me know?  https://github.com/swagger-api/swagger-node/issues/294

**Comment by vincpa** [comment]
Sure I'll try

**Comment by darkyen** [comment]
Its fixed.

**Comment by theganyo** [comment]
Awesome. Thanks for checking!

**Comment by bchr02** [comment]
@theganyo I am still not able to use the arrow keys, even with the current version of node-swagger  0.7.5.

**Comment by eftalersoy** [comment]
same here

**Comment by darkyen** [comment]
I am just curious have you guys tried it on cmder or conemu ? For me it works on all consoles but just wondering.

**Comment by eftalersoy** [comment]
I just used windows cmd.
