### ISSUE TITLE
Order validation

### ISSUE THREAD

**Issue by mustafamamun** [swagger-api/swagger-node#287]
Is there a way to force the incoming JSON to follow some order. What I mean is I want a JSON like this
```json
"Object": {
			"key1": "value1",
			"key2": "value2",
			"key3": "value3",
			"key4": "value4",
			"key5": "value5"
		 }
```
 Not like this
```json
"Object": {
			"key1": "value1",
			"key2": "value2",
                        "key5": "value5",
			"key3": "value3",
			"key4": "value4"
		 }
```
Or any other order.

I know it is wired but believe me  I i need it.

**Comment by webron** [comment]
According to the JSON specification, `An object is an unordered set of name/value pairs.` - this means that the order is never guaranteed. If you need to preserve order, you should opt for an array.

**Comment by mustafamamun** [comment]
This is a simple example that I have given. The schemas are very complex they have 3rd level nested object. It is not possible to put them in array and they need to follow some specific schema if one object come before another one the system throws error.

**Comment by webron** [comment]
Not really sure how you want something that behaves as defined to behave differently.

**Comment by mustafamamun** [comment]
I do not want to but I have to. I know It is weird however I was hopping if there is a way otherwise I have to do it by myself in my code.

**Comment by jhurliman** [comment]
Define your own serializer? This goes outside of the JSON spec.
