### ISSUE TITLE
Generate Node.JS code from swagger?

### ISSUE THREAD

**Issue by SamuelMarks** [swagger-api/swagger-node#292]
I know there are other projects from swagger that can generate Node.JS code from the Swagger YAML, but AFAIK only swagger-node supports multiple different Node.JS web frameworks.

So is there a step after I've updated my YAML to also generate the tests and server stubs?

EDIT: Thus far I have tried `swagger-codegen` (which created Connect) and [swagger-js-codegen](https://github.com/wcandillon/swagger-js-codegen) (which created a Node.js object)

**Comment by theganyo** [comment]
There currently is no command to generate the controller stubs for you (we may be adding that soon)... but if you take a look at the hello_world controller, you can see that there is almost no boilerplate and the stubs are extremely simple to create by hand and extend.

As for tests, there is a command: `swagger project generate-test` that will generate an initial test framework for you. Use `swagger project generate-test -h` to see the options available for you to customize this to your liking.
