### ISSUE TITLE
Error: Response validation failed: failed schema validation with format "date-time"

### ISSUE THREAD

**Issue by glederrey** [swagger-api/swagger-node#293]
Hi,

I just experienced a weird error.. I'm using swagger node to create a mock server with my spec.. I found that there is a 500 error if we set a value like this:
    `"doc_created": {
    "type": "string",
    "format": "date-time"
    }`
I have the same error if I use the format "date". But without any format, it's working fine.. Do you think that, currently, swagger-node cannot produce a mock server sending "date-time" and "date" format responses?? 

Thanks in advance

**Comment by whitlockjc** [comment]
Can you run with `DEBUG=swagger-tools*` and give us the stacktrace?

**Comment by glederrey** [comment]
Hi,

Thanks your your reply.. Here is what I got using the command `swagger project start DEBUG=swagger-tools* -m`

    Error: Response validation failed: failed schema validation
    at throwErrorWithCode (/home/gael/Desktop/swagger-test/test-node/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/lib/validators.js:121:13)
    at Object.module.exports.validateAgainstSchema (/home/gael/Desktop/swagger-test/test-node/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/lib/validators.js:150:7)
    at /home/gael/Desktop/swagger-test/test-node/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/middleware/swagger-validator.js:141:22
    at /home/gael/Desktop/swagger-test/test-node/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/async/lib/async.js:358:13
    at /home/gael/Desktop/swagger-test/test-node/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/async/lib/async.js:239:13
    at _arrayEach (/home/gael/Desktop/swagger-test/test-node/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/async/lib/async.js:91:13)
    at _each (/home/gael/Desktop/swagger-test/test-node/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/async/lib/async.js:82:13)
    at async.forEachOf.async.eachOf (/home/gael/Desktop/swagger-test/test-node/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/async/lib/async.js:238:9)
    at _asyncMap (/home/gael/Desktop/swagger-test/test-node/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/async/lib/async.js:357:9)
    at Object.map (/home/gael/Desktop/swagger-test/test-node/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/async/lib/async.js:340:20)

If you want, I have a simple cherrypy server running the documentation locally plus swagger-node used as a mock server running with three options to get a json response with a string and different formats.. 

Best

**Comment by whitlockjc** [comment]
Can you tell me the request you're making?  Also, the failure of schema validation should show the reasons it failed but if not, you could add an error handler to your server and print `err.errors`

**Comment by glederrey** [comment]
It's a simple get request.. The error comes when I call the get requests from the endpoints `json/date` and `json/datetime`.. You'll find the JSON file at the end of this message.. Of course, it's not the JSON file I'm using for my real API, but it's just an example of what is not working.. 

How can I handle the errors?? I mean, do you want me to change the code after I created the project?? If yes, I'll do this tomorrow and will post the answer here.. 

Here is the JSON file: 
```
{
  "swagger": "2.0",
  "basePath": "/path",
  "schemes": [
    "http",
    "https"
  ],
  "host": "localhost:10010",
  "info": {
    "description": "Dummy description",
    "version": "1.0",
    "title": "Dummy Title",
    "contact": {
      "email": "foo@bar.ch"
    }
  },
  "consumes": [
    "application/json",
    "text/html"
  ],
  "produces": [
    "application/json",
    "text/html",
    "multipart/form-data"
  ],
  "paths": {
    "/json/datetime": {
      "get": {
        "responses": {
          "200": {
            "description": "Success!!", 
             "schema": {
              "$ref": "#/definitions/datetime"
            }
          }, 
          "403": {
            "description": "Request could not be authorized."
          }, 
          "400": {
            "description": "Malformed request."
          }
        }, 
        "description": "Get a JSON response with format date-time", 
        "parameters": [
          {
            "description": "dummy parameter", 
            "required": true, 
            "type": "string", 
            "name": "dummy", 
            "in": "query"
          }
        ], 
        "tags": [
          "JSON"
        ]
      }
    }, 
    "/json/date": {
      "get": {
        "responses": {
          "200": {
            "description": "Success!!", 
             "schema": {
              "$ref": "#/definitions/date"
            }
          }, 
          "403": {
            "description": "Request could not be authorized."
          }, 
          "400": {
            "description": "Malformed request."
          }
        }, 
        "description": "Get a JSON response with format date", 
        "parameters": [
          {
            "description": "dummy parameter", 
            "required": true, 
            "type": "string", 
            "name": "dummy", 
            "in": "query"
          }
        ], 
        "tags": [
          "JSON"
        ]
      }
    },   
    "/json/normal": {
      "get": {
        "responses": {
          "200": {
            "description": "Success!!", 
             "schema": {
              "$ref": "#/definitions/normal"
            }
          }, 
          "403": {
            "description": "Request could not be authorized."
          }, 
          "400": {
            "description": "Malformed request."
          }
        }, 
        "description": "Get a JSON response without the format", 
        "parameters": [
          {
            "description": "dummy parameter", 
            "required": true, 
            "type": "string", 
            "name": "dummy", 
            "in": "query"
          }
        ], 
        "tags": [
          "JSON"
        ]
      }
    }
  }, 
  "definitions": {
    "datetime": {
      "type": "object",
      "properties": {
        "dummyString": {
          "type": "string",
          "format": "date-time"
        }
      },
      "example": {
        "dummyString": "1997-07-16T19:20:30.45+01:00"
      }
    },
    "date": {
      "type": "object",
      "properties": {
        "dummyString": {
          "type": "string",
          "format": "date"
        }
      },
      "example": {
        "dummyString": "1997-07-16"
      }
    },
    "normal": {
      "type": "object",
      "properties": {
        "dummyString": {
          "type": "string"
        }
      },
      "example": {
        "dummyString": "I'm a dummy string."
      }
    }
  }
}```

**Comment by whitlockjc** [comment]
I didn't need the schema.  :)  I wanted an example of the value you are passing to your API that is triggering the schema validation failure.  So...based on the example above, what value are you passing as a query string for `dummy`?

**Comment by glederrey** [comment]
Hi,

I just pass something like one letter or one number.. But the problem doesn't comes from here.. (I could have get rid of the parameters in my example.. (I just updated it))

Just one other thing.. I changed the 200 response to have something like that:
    ```"200": {
      "description": "Success!!", 
        "schema": {
          "type": "string",
          "format": "date-time"
        }
    }```
And here is the error I got: 
`Error: Response validation failed: not a valid date-time string: &quot;Sample text&quot;<br> &nbsp; &nbsp;at throwErrorWithCode`

So, is it possible that the mock server (using -m) has not the format date and date-time implemented?? 

Thanks

**Comment by whitlockjc** [comment]
I was crossing the streams, response validation failed.  Seems like mock support does not work with date-time formatted strings.  I'll file a bug.

**Comment by glederrey** [comment]
Okay, thanks..

**Comment by whitlockjc** [comment]
This is fixed in `swagger-tools@master` and will be released soon.

**Comment by musman92** [comment]
use swagger project verify
it will give you the exact line no of error occurrence
