### ISSUE TITLE
Swagger-node beta feedback

### ISSUE THREAD

**Issue by theganyo** [swagger-api/swagger-node#294]
#### Swagger-node beta released for feedback...

New features:
* Request handing pipeline is now fully [configurable](https://github.com/swagger-api/swagger-node/blob/bagpipes/docs/configuration.md)
* mapErrorsToJson should now work in all environments
* Security handlers can be declared in config in app.js...
```js
config.swaggerSecurityHandlers = {
  oauth2: function securityHandler1(req, authOrSecDef, scopesOrApiKey, cb) {
    // whatever
    cb();
  }
};
```

-------

Please give it a try and let me know what you think...

```
npm install swagger@beta -g
swagger project create
```

New configuration documentation: 
https://github.com/swagger-api/swagger-node/blob/bagpipes/docs/configuration.md

-----

Note: To convert an existing swagger-node application:
1. Update your package.json to use the beta middleware versions: "^0.1.0". (ie: `"swagger-connect": "^0.1.0"`)
2. Update your application dependencies: `npm update`.
3. Run it.
4. Note: Existing config will work **in general** (expcept swagger_docs), but you should really update your config to the new format.

-----

Also, by the way, if you're really into it, here are a couple of really contrived examples of using Bagpipes instead of code: https://github.com/apigee-127/bagpipes-examples

**Comment by molexx** [comment]
Hi, thanks for this, trying it out with sails. Is swagger-sails-hook still needed as a dependency in package.json?

**Comment by theganyo** [comment]
@molexx Yes, it still runs on Sails via the hook.

**Comment by theganyo** [comment]
New feature: Application configuration is now driven by config module to allow a ton of flexibility in setting up configurations and routes based on environment. See: https://github.com/lorenwest/node-config/wiki/Configuration-Files

**Comment by darkyen** [comment]
awesome @theganyo

**Comment by theganyo** [comment]
Beta has now been released as latest
