### ISSUE TITLE
DELETE Routes Never neve response or Time out if configured

### ISSUE THREAD

**Issue by oliverhr** [swagger-api/swagger-node#297]
On any defined route for DELETE verb it always hangs or timeed out if configured, all this happen on second calls. 

No matter if code is simple as this:

```
function remove(req, res, next) {
  res.statusCode = 500;
  res.json( {message: 'ERROR MESSAGE'} );
}
```

```
function remove(req, res, next) {
  // This is intercepted with a custom error handler
  next( {message: 'ERROR MESSAGE'} );
}
```

i dont know if this happen to anyone else.

```
Swagger version 0.6.3
swagger-express-mw version 0.0.4
express version 4.13.3
```

**Comment by theganyo** [comment]
I just tried this: 
* Created a new project
* Added a delete route in the Swagger to the /hello path
* Exported a new controller function for delete to hello_world.js
* Started the project
* Executed a curl -X DELETE request against it

I have the same versions as you and the request worked as expected. So it looks like something else may be going on. Can you try this simple test as well?

**Comment by oliverhr** [comment]
Yes you're right I checked even with this code in order to visually check the response more clear.

```
function bye(req, res, next) {
  bye.counter = ++bye.counter || 0;
  var name = req.swagger.params.name.value || 'stranger';
  res.json('Bye, ' +  name + ' by ' + bye.counter + ' time');
}
```

Thank you.
