### ISSUE TITLE
Mock Mode Not Working

### ISSUE THREAD

**Issue by kadjei** [swagger-api/swagger-node#302]
With package version `"swagger-express-mw": "^0.1.0"` mock mode is no longer working with cmd `swagger project start -m`

**Comment by theganyo** [comment]
My apologies for that. I was already looking into it, so here's a quick fix!

**Comment by kadjei** [comment]
@theganyo  Thank You its working now

**Comment by dmitry-zaets** [comment]
Hi @theganyo,
Probably I'm doing something wrong, but clean installation of swagger still not working when running ```swagger project start -m```
As far as I understand, you have updated version of ```swagger-node-runner```, but have not updated version of it in swagger-node.
