### ISSUE TITLE
404 error for sub collection resource

### ISSUE THREAD

**Issue by kadjei** [swagger-api/swagger-node#305]
Im getting a 404 not found error for my sub collection resource endpoint.
but according to my debug output everything should be working.

```
/collection/{resource}/subcollection/{resource}
```
```
swagger-tools:middleware:metadata GET /collection/123/subcollection/34 +3m
  swagger-tools:middleware:metadata   Is a Swagger path: true +0ms
  swagger-tools:middleware:metadata   Is a Swagger operation: true +0ms
  swagger-tools:middleware:metadata   Processing Parameters +0ms
  swagger-tools:middleware:metadata     collectionId +0ms
  swagger-tools:middleware:metadata       Type: string +1ms
  swagger-tools:middleware:metadata       Value provided: true +0ms
  swagger-tools:middleware:metadata       Value: 123 +0ms
  swagger-tools:middleware:metadata     subcollectionId +0ms
  swagger-tools:middleware:metadata       Type: string +0ms
  swagger-tools:middleware:metadata       Value provided: true +0ms
  swagger-tools:middleware:metadata       Value: 34 +0ms
```

**Comment by whitlockjc** [comment]
Can you paste the `swagger-tools:middleware:router` details?  We have debugging that will help us.

**Comment by kadjei** [comment]
The only swagger-tools middleware firing at this endpoint is `swagger-tools:middleware:metadata`
The rest of swagger-tools middlewares do not get called.
My GET request gets sent down to my Error handler but all other HTTP verbs produce `Cannot {HTTP verb} /collection/{resource}/subcollection/{resource}`

**Comment by fehguy** [comment]
I suggest you change the path parameters to be unique.  `resource` in two places may cause a problem.

**Comment by kadjei** [comment]
@fehguy My previous comment was just to showcase the structure of my endpoint.
My actually implementation is using unique parameters.
```
/collection/{collectionId}/subcollection/{subcollectionId}
```

**Comment by whitlockjc** [comment]
If swagger-router is not being used, the request will fall through and you'll get a 404.  But I'm not sure how swagger-router wouldn't be used.  Can you paste your operation definition?

**Comment by kadjei** [comment]
Endpoint 
```
/collection/{collectionId}/subcollection/{subcollectionId}/:
    parameters:
      - $ref: "#/parameters/collectionId" 
      - $ref: "#/parameters/subcollectionId" 
    get:
      description: Get subcollection by id
      operationId: getSubcollection
      responses:
        200:
          description: Successfully retrieved subcollection
          schema:
            $ref: "#/definitions/subCollectionModel"
        default:
          description: Error retrieving subcollection
          schema:
            $ref : "#/definitions/errorResponse"
    put:
      description: Update subcollection by id
      operationId: updatesubcollection
      parameters:
        - name : subCollectionModel 
          in: body
          required: true
          description: subcollection Model
          schema:
            $ref: "#/definitions/subCollectionModel"
      responses:
        200:
          description: Successfully updated subcollection
          schema:
            $ref: "#/definitions/successResponse"
        default:
          description: Error updating subcollection
          schema:
            $ref : "#/definitions/errorResponse"
    delete:
      description: delete subcollection by id
      operationId: deletesubcollection
      responses:
        200:
          description: Successfully deleted subcollection
          schema:
            $ref: "#/definitions/successResponse"
        default:
          description: Error deleting subcollection
          schema:
            $ref : "#/definitions/errorResponse"
```
Definitions/Parameters
```
definitions:
  subCollectionModel:
    required:
      - name
      - description
    properties:
      name:
        type: string
      description:
        type: string
  errorResponse:
    required:
      - status
      - message
    properties:
      status:
        type: number
      message:
        type: string
parameters:
  collectionId:
    name: collectionId
    description: collection Id
    in: path
    type: string
    required: true
  subcollectionId:
    name: subcollectionId
    description: subcollection Id
    in: path
    type: string
    required: true
```

**Comment by kadjei** [comment]
I found the culprit i never specified a ` x-swagger-router-controller` for the endpoint.
is it possible to throw an error when this happens.

**Comment by whitlockjc** [comment]
Can you tell me which version of swagger-tools you have?  `npm ls | grep 'swagger-tools'`  But even with `x-swagger-router-controller` missing, you should see the `swagger-tools:middleware:router` output and it should throw a `500`.

**Comment by kadjei** [comment]
`swagger-tools@0.9.6`

**Comment by whitlockjc** [comment]
I think what is happening is that swagger-node-runner conditionally handles controllers based on the existence of `x-swagger-router-controller` which is why I expected it to work one way but it is not.  swagger-tools by itself works like you want but it seems swagger-node-runner circumvents the swagger-tools routing if `x-swagger-router-controller` is missing.  This is what I'm talking about: https://github.com/theganyo/swagger-node-runner/blob/b5100892737669109f21f12f42b77f2dc264509a/index.js#L114

I'll let @theganyo confirm this and we'll come up with a solution then.

**Comment by kadjei** [comment]
Sounds great.
Thank you

**Comment by theganyo** [comment]
This is by intention. Not every declared route needs to be run by swagger-router.

**Comment by kadjei** [comment]
Just to understand in what circumstance would it by beneficial to declare a route without a controller. because with this design it looks like the only swagger tool middleware firing is `swagger-tools:middleware:metadata` which produces a 404 error even without my 404 error hander.

**Comment by whitlockjc** [comment]
swagger-tools never produces a 404 but that it does that leads to a 404 is it sends the request to downstream middleware and the default server middleware is creating a 404.  As for not using `x-swagger-router-controller`, that's useful when your server environment owns routing or when you want to have your own route handler that does not operate within the swagger-tools middleware chain.

My two cents.

**Comment by kadjei** [comment]
My initials thoughts In that case would be to specify that specific route outside my swagger yaml file and instead use express/connect to handle that route.

@whitlockjc  Thank you that gives me some insight on some alternative conventions.

**Comment by whitlockjc** [comment]
Please let us know if we can do things better.  If you have a use case we don't support, it doesn't mean it shouldn't be supported.

**Comment by kadjei** [comment]
To the best of my knowledge if i have a route specified in swagger without a controller, i would have to specify that route again in connect/express which would make my route inside swagger redundant. 
But if swagger had something along the lines of the code sample below, then that would remove the need to specify the route again in connect/express.

This is all due to my limited knowledge on routing in swagger without a controller.

```
/collection/{resource}:
  x-{express/connect}-router-controller: resource
  parameters:
    - $ref: "#/parameters/resourceId"
  get:
    parameters:
      - $ref: "#/parameters/resourceGetModel"
    responses:
      200:
        description: Resource View
        view:
          $ref: "#/views/resourceTemplate"
      default:
        description: 404 View
        view:
          $ref: "#/views/404Template"
  Post:
    parameters:
      - $ref: "#/parameters/resourcePostModel"
    responses:
      200:
        parameters: 
          {post response resource}
        description: Resource Post Action
        view:
          $ref: "#/views/resourceTemplate"
      default:
        description: 404 View
        view:
          $ref: "#/views/404Template"
definitions:
  resourceGetModel:
    properties:
      {Response data}
  resourcePostModel:
    properties:
      {Response data}
parameters:
  resourceId:
    name: resourceId
    in: path
    type: string
    required: true 
```

**Comment by theganyo** [comment]
I'm not sure exactly why you're avoiding controllers, but you can do just about anything you want very easily by adding "x-swagger-pipe" to any path and defining a pipe to play in the config. 

As an example, this path is in the default swagger.yaml you get with a new project:

```yaml
  /swagger:
    x-swagger-pipe: swagger_raw
```

And this is in the config/default.yaml:
```
    # pipe to serve swagger (endpoint is in swagger.yaml)
    swagger_raw:
      name: swagger_raw
```

This just says that if you hit the /swagger endpoint, you will run the [swagger_raw](https://github.com/theganyo/swagger-node-runner/blob/master/fittings/swagger_raw.js) fitting predefined in swagger-node-runner.

And, you can add custom fittings that do whatever you'd like by just creating a node module in the api/fittings directory. The signature is very simple:

```
module.exports = function create(fittingDef, bagpipes) {
  return function exec(context, cb) {
      cb();
    });
}
```

See also the [configuration documentation](https://github.com/swagger-api/swagger-node/blob/master/docs/configuration.md).

Is that what you're looking for?
Scott

**Comment by kadjei** [comment]
I'm still using controllers but after finding out i can specify a route without a controller, i became interested in why that would be intentional by design.
But your comment reflects exactly what i thought would be possible.

@theganyo Thank You
