### ISSUE TITLE
Is it possible to create an api doc for an existing application written with nodejs/express ?

### ISSUE THREAD

**Issue by AshutoshKumar** [swagger-api/swagger-node#306]

**Comment by theganyo** [comment]
I'm not aware of any tool that will generate a Swagger document from your Express routes, but it should be possible to at least generate a skeleton, so I wouldn't be surprised if there was one.

**Comment by DinisCruz** [comment]
Any more new on this? 

I would like to use this to calculate the attack surface of existing node/express apps

**Comment by fehguy** [comment]
Depending on how your existing app is written, you can probably leverage swagger-node to connect the definition to your existing controllers.  That does mean someone will have to write the swagger definition itself--which may be what you're trying to find a tool to do--but then you'd be able to leverage the swagger-node project.
