### ISSUE TITLE
Why is JsonErrorHandler the first middleware?

### ISSUE THREAD

**Issue by Hanspagh** [swagger-api/swagger-node#307]
For me this is causing validation errors to be returned as HTML and not as JSON?
Putting the JsonErrorHandler as the last middleware fixes this. Is there a specific reason for having it first?

**Comment by theganyo** [comment]
Are you referring to the `onError:` operation on the pipe? That fitting just registers the handler for future operations, so what you're describing would be unexpected unless something else is going on. Are you talking about swagger-tools response validation errors? Or something else?

**Comment by Hanspagh** [comment]
As I am having the problem in #303 I am referring to the old version without the pipes

**Comment by Hanspagh** [comment]
I now tried with the new version, I am still getting request validations errors returned as html and not as Json. Is this the expected behavior or am I missing something.

**Comment by theganyo** [comment]
What container are you using?

**Comment by Hanspagh** [comment]
Do you mean as in framework, then it is express.

**Comment by theganyo** [comment]
Thank you for your patience. The issue has been fixed in swagger-node-runner. Please let me know how it goes.

**Comment by Hanspagh** [comment]
Awesome, will have a look at it tomorrow

**Comment by Hanspagh** [comment]
Now it return as json, which is awesome, but all errors are now http 500 errors :(

**Comment by theganyo** [comment]
What errors? Where and how are they being generated? What are you expecting the error handler to do with them other than translate to 500?

**Comment by Hanspagh** [comment]
Previously request validation errors was returned with error code 400, which makes sense since it's a client error and not a server error

**Comment by theganyo** [comment]
Oh, the validator. Yes, of course. I'll look into that.

**Comment by theganyo** [comment]
Ok. I've updated it. The error handler is now much more careful about not overriding existing error codes. Thanks again!

**Comment by Hanspagh** [comment]
Works perfectly
