### ISSUE TITLE
Uncaught HTTP verbs by error handler

### ISSUE THREAD

**Issue by kadjei** [swagger-api/swagger-node#308]
per debug output `swagger-tools:middleware:metadata   Is a Swagger path: false`
all HTTP verbs except for GET never gets caught by error handler.

**Comment by whitlockjc** [comment]
What happens is if you request a path that is not a Swagger path, none of the middlewares will do anything and will just send the request downstream.  Now if the request is for a Swagger path but there is no Swagger operation defined, you will get a `405`.  Since your debug output matches that of the first scenario, what is happening is by design.

Since this seems to be unexpected, I need to know your path definition string and the request path to help further.

**Comment by kadjei** [comment]
Thats exactly what i expected but `swagger-tools:middleware:metadata` still gets called.
below is the complete debut output.
```
swagger-tools:middleware:metadata PUT /users +1m
swagger-tools:middleware:metadata   Is a Swagger path: false +0ms
```
I don't have a `/users` endpoint specified in my swagger spec.

below is my cURL output
```
> POST /users HTTP/1.1
> Host: localhost:10010
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET,PUT,POST,DELETE
< Connection: close
< X-Content-Type-Options: nosniff
< Content-Type: text/html; charset=utf-8
< Content-Length: 19
< Date: Thu, 08 Oct 2015 15:19:55 GMT
<
Cannot POST /users
* Closing connection 0
```

**Comment by whitlockjc** [comment]
It's working as designed.  All of the middleware provided by swagger-tools, which is what swagger-node uses, are only interested in Swagger paths.  If you request a path that is not a Swagger path, we send the request downstream to allow other parts of your server to get involved.

There has been some requests to make swagger-node/swagger-tools have some *"strict mode"* where you'd error on non-Swagger paths, error on undefined parameters, etc.  But that is not available as of now.

That being said, swagger-node does not care that you requested a path that is not a Swagger defined path and will send the request downstream.

**Comment by theganyo** [comment]
I don't understand what behavior you're expecting. Are you saying that you want your error handler to be able to capture 404s?

**Comment by whitlockjc** [comment]
If I understand correctly, @kadjei wants an error to be thrown whenever a request is made to a path that is not a Swagger path instead of the request falling through and resulting in a 404.

**Comment by kadjei** [comment]
Its exactly as described by @theganyo and i have a method to handle 404s as show below.
```
// 404 Errors
app.get('*',function(req,res,next){
   res.status(404);
   var response = {"code": "NOT_FOUND","message" : "Resource not available"};
   logging.info(response);
   res.json(response);
   next(err);
});
      
// All Errors
app.use(function(err,req,res,next){
   res.set("Content-Type","application/json");
   logging.error(err);
   res.json(err);
})
```
I get the expected behavior for GET requests but all other HTTP verbs product `Cannot {HTTP verb} /users`

**Comment by theganyo** [comment]
Your first handler is only capturing "get" requests (app.get). Is that the problem?

**Comment by kadjei** [comment]
@theganyo That was an oversight on my end should've had a co-worker look at it before posting an issue.
Thank you

**Comment by kadjei** [comment]
On another note you guys are doing great work on this project.
Thank you both.

**Comment by theganyo** [comment]
Awesome, @kadjei. Glad it's worked out! :)

**Comment by whitlockjc** [comment]
Thanks @kadjei.
