### ISSUE TITLE
New project throwing error when calling example API endpoint

### ISSUE THREAD

**Issue by gargantuan** [swagger-api/swagger-node#309]
If I create a new project as follows

```
swagger project create test
...[choose framework]
swagger project start test
```

I'm greeted with this message

```
Starting: /Users/gargantuan/Desktop/test/app.js...
  project started here: http://localhost:10010/
  project will restart on changes.
  to restart at any time, enter `rs`
try this:
curl http://127.0.0.1:10010/hello?name=Scott
```

However, if I call that endpoint using curl or via the browser, I get this error.

```
TypeError: undefined is not a function
    at applyHeaders (/Users/gargantuan/Desktop/test/node_modules/cors/lib/index.js:146:15)
    at applyHeaders (/Users/gargantuan/Desktop/test/node_modules/cors/lib/index.js:142:11)
    at applyHeaders (/Users/gargantuan/Desktop/test/node_modules/cors/lib/index.js:142:11)
    at cors (/Users/gargantuan/Desktop/test/node_modules/cors/lib/index.js:177:7)
    at /Users/gargantuan/Desktop/test/node_modules/cors/lib/index.js:228:17
    at originCallback (/Users/gargantuan/Desktop/test/node_modules/cors/lib/index.js:217:15)
    at /Users/gargantuan/Desktop/test/node_modules/cors/lib/index.js:222:13
    at optionsCallback (/Users/gargantuan/Desktop/test/node_modules/cors/lib/index.js:203:9)
    at /Users/gargantuan/Desktop/test/node_modules/cors/lib/index.js:208:7
    at null.<anonymous> (/Users/gargantuan/Desktop/test/node_modules/bagpipes/lib/bagpipes.js:171:7)
```

I've tested using every framework and I get the same error.

**Comment by theganyo** [comment]
It appears to be an issue in the cors module. I'll look into it, but I believe removing cors from your swagger_controllers pipeline in config/default.yaml will give you quick relief.

**Comment by theganyo** [comment]
@gargantuan On further review, it actually looks like it's related to npm version 3.x.x. What version are you on? If you're on 3, could you try deleting your app's node_modules and install with npm@2.14.4 and try again?

**Comment by gargantuan** [comment]
I was running npm@3.3.4

Downgrading to npm@2.14.4 works so thanks for the heads up. Do you know if this is this a problem with npm, the package or a particular dependency?

**Comment by theganyo** [comment]
No, unfortunately, I don't know how the new npm is messing things up yet.

**Comment by whitlockjc** [comment]
It would be interesting to see the output of `npm ls` for both versions of NPM to see what is different, specifically for the `cors` module.

**Comment by theganyo** [comment]
This has been fixed. It was related to having node_modules listed as a fittings directory. For existing projects, just remove node_modules from the fittings in your config to fix it.
