### ISSUE TITLE
JsonErrorHandler

### ISSUE THREAD

**Issue by Hanspagh** [swagger-api/swagger-node#311]
Could the jsonErrorHandler check the status code of the error being thrown, and respond with that code. That would make it possible for custom errors to have other error codes than 500.

**Comment by theganyo** [comment]
Hi Hans. Let me restate: You'd like to be able to provide a "statusCode" attribute on the error that you throw that is checked by the handler and, if present, assigned to the statusCode of the response. Is that correct?

**Comment by Hanspagh** [comment]
Correct, unless there some other way for me to give my own errors others error codes then 500. I could properly do a pr. if this is something you think is a good idea.

**Comment by theganyo** [comment]
I don't have a problem with that. (FYI: The current error handler will preserve an error code on the response if you set it, so that's another possibility.)

**Comment by Hanspagh** [comment]
I will look into the pr. I guess the validator makes use of the preserved response code. But I think it's  more clean to have it tied to the actual error
