### ISSUE TITLE
Limit size of uploaded files

### ISSUE THREAD

**Issue by Hanspagh** [swagger-api/swagger-node#314]
Is it possible to access to Multer, to restrict the size of uploaded files?

**Comment by whitlockjc** [comment]
We provide request parsers as a convenience.  If you need to customize them, wire in the parser yourself with your own configuration.  Just make sure to use the same multer version swagger-tools provides.

**Comment by Hanspagh** [comment]
Sorry for the late response. I am bit unsure on how you would do that without changing the files in the node_modules folder?

**Comment by theganyo** [comment]
You would just install your handler in app.js and ensure that it runs before the swagger handlers. For example, I think with the version of multer that swagger-tools uses it would look something like:

```
SwaggerExpress.create(config, function(err, swaggerExpress) {
  if (err) { throw err; }

  var mult = require('multer')({/* your multer options */});
  app.use(mult);

  // install middleware
  swaggerExpress.register(app);
```

(BTW: All of this is the process of being rewritten without swagger-tools and will be exposing the parser configs directly.)

**Comment by Hanspagh** [comment]
Awesome thanks. Will implement this.
Looking forward to the the changes :+1:
