### ISSUE TITLE
x-swagger-router-controller in documentation?

### ISSUE THREAD

**Issue by BerndErnst** [swagger-api/swagger-node#337]
I'm asking myself where the x-swagger-router-controller documentation should be.

**Comment by fehguy** [comment]
It is used to map operations to controllers, and therefore it lives at the same level as the `nickname` or other operation:  https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operationObject

**Comment by whitlockjc** [comment]
https://github.com/apigee-127/swagger-tools/blob/master/docs/Middleware.md#swaggerrouteroptions

**Comment by BerndErnst** [comment]
fehguy:
Exactly, on this place I'm missing more information.
whitlockjc:
I would have never found it there.

**Comment by whitlockjc** [comment]
Easy to miss, swagger-tools is hidden.
