### ISSUE TITLE
Update to swagger-express-mw 0.6.0 ?

### ISSUE THREAD

**Issue by oliverhr** [swagger-api/swagger-node#345]
Any plan to update to swagger-express-mw 0.6.0 ?
Or a guide to use with generated swagger-node projects?

**Comment by molokoloco** [comment]
Hi,
i have trouble with nodemon.. i have found the related code here (In GLOBAL :-( node_modules) :

> /usr/lib/node_modules/swagger/lib/commands/project/project.js

But i can't manage to see what going wrong, the project start, but nodemon is not correctly watching.
I see nothing wrong with "DEBUG=* swagger project start"
But when i do :

```
ubuntu1@ubuntu1-VirtualBox:~/www/bytel_api$ swagger project start
Starting: /home/ubuntu1/www/bytel_api/app.js...
  project started here: http://127.0.0.1:10010/v2
  project will restart on changes.
  to restart at any time, enter `rs`
ubuntu1@ubuntu1-VirtualBox:~/www/bytel_api$ try this:
curl http://127.0.0.1:10010/hello?name=Scott
```

After that "rs" command is not found and node is a ghost process (have to kill it with "killall -9 node")
Normally i have this:

```
ubuntu1@ubuntu1-VirtualBox:~/www/bytel_api$ swagger project start
Starting: /home/ubuntu1/www/bytel_api/app.js...
  project started here: http://127.0.0.1:10010/v2
  project will restart on changes.
  to restart at any time, enter `rs`
try this:
curl http://127.0.0.1:10010/hello?name=Scott
```

After some updates of somes node_modules, i have downgraded my package.json with
"swagger-express-mw": "^0.1.0"
Removed and reinstalled... was working yesterday, but this morning, nope. Weird bug with no trace.

**Comment by Hanspagh** [comment]
+1

**Comment by ronkot** [comment]
+1
Doesn't work with swagger-express-mw 0.6.0 and current documentation. It seems that `req.swagger.params` doesn't get populated.

**Comment by molokoloco** [comment]
@ronkot i can advise you that it works better for me now with this code...
=> https://www.npmjs.com/package/swagger-tools
You can forget "swagger-express-mw"...

```
'use strict';

var swagger = require('swagger-tools');
var express = require('express');
var http = require('http');

var swaggerObject = require('./api/swagger/swagger.json');

var app = express();

swagger.initializeMiddleware(swaggerObject, function(middleware) {

    app.use(middleware.swaggerMetadata());
    app.use(middleware.swaggerValidator());
    app.use(middleware.swaggerRouter({useStubs: true, controllers: './api/controllers'}));
    app.use(middleware.swaggerUi());

    http
        .createServer(app)
        .listen(80);
});
```

**Comment by ronkot** [comment]
Thanks, @molokoloco! Your approach worked perfectly. Just had to add cors middleware (using cors npm module).

**Comment by AmreeshTyagi** [comment]
@molokoloco How you are dealing with oauth2 security with swagger-tools. I am using `swagger-express-mw` and following is my approach for oauth2 
`var SwaggerExpress = require('swagger-express-mw')
var swaggerConfig = {
  appRoot: __dirname, // config.get('api').API_BASE_URI, // required config
  swaggerSecurityHandlers: {
    apiKey: services.authService.validateHeader,
    accessToken: services.authService.authorizeToken
  }
}`
`SwaggerExpress.create(swaggerConfig, function (err, swaggerExpress) {
  if (err) {
    throw err
  }

  // install middleware
  swaggerExpress.register(app)
)` 

This is working perfectly fine. But not sure about swagger-tools. any idea?

**Comment by oliverhr** [comment]
The thing is that since version 0.6.0 swagger-node-runner no longer use swagger-tools, it was replaced with sway.

If you use the express middleware the dependency chain looks like this

0 - swagger-node
1 - swagger-express-mw
2 - swagger-node-runner "swagger-node-runner": "^0.6.1"
3 - "sway": "^0.3.2"
...

https://github.com/apigee-127/sway

**Comment by pourquoi42** [comment]
@oliverhr: this doesn't really address the question.

I am also stuck. I need some features/fixes that are in later of  swagger-express-mw. But I can't just replace it, or I face the same issue that @ronkot  described. Basically, my existing project doesnt work any more. I am very tempted to follow the adivse of molokoloco, yet I am totally confused about the roadmap: if sway replaces swagger-tools, does it mean swagger-tools will be abandoned ??? And if the swagger-tools direction is not the way to go, then can someone please advise on the original question, how to upgrade swagger-node-mw ? (If you use this project as is, you get swagger-node-mw v0.1.0 which has horrible bugs)

**Comment by stv8** [comment]
I want to add that I was having many problems with `swagger-express-mw` and using @molokoloco solution worked out the best.

**Comment by Mojo90** [comment]
#460 should fix that ;)

**Comment by cadriel** [comment]
If the skeleton is now not the preferred approach, what would the app.js look like?
