### ISSUE TITLE
Use Swagger.json instead of Swagger.yaml

### ISSUE THREAD

**Issue by AmrEldib** [swagger-api/swagger-node#346]
I was wondering if I can use the JSON file instead of YAML to generate the API.
One quick way to do this is to convert the JSON file to YAML and still rely on YAML.
When the user passes an argument (say `--json`) to the CLI on `project start` then swagger would monitor the JSON file and convert it to YAML every time it's updated.
### Current Workaround
I copy the JSON to swagger editor, and use Paste as JSON. Then, copy the YAML and save it to file.
This workaround isn't enough because it's very time consuming.
### Why use JSON
I use Visual Studio to write the JSON, it has a excellent JSON validation and intellisense against the swagger schema. It helps write and discover the schema as I type.
### Other Possible Solution
CLI or NPM package that can convert JSON to YAML. As I write this, I did a quick search and found [json2yaml](https://www.npmjs.com/package/json2yaml), I'll try it and see if helps solve the problem. But I still would like if this is included out of the box

**Comment by AmrEldib** [comment]
[json2yaml](https://www.npmjs.com/package/json2yaml) seems to do the trick even if it adds a triple dash --- at the start of the file. I'm not that familiar with YAML, maybe it's part of the syntax.

**Comment by webron** [comment]
The triple dash is part of the YAML syntax, it's a document separator. When there's only one document, it's not required, but it doesn't harm anything if it's there.

**Comment by gutenye** [comment]
Why not support the json format?

**Comment by fehguy** [comment]
swagger-node combines the editor and a node middleware.  So because of that, it is tailored to the yaml format.

Remember that you can use the middleware without the swagger-node editor.
