### ISSUE TITLE
"swagger project edit" support for npm@3 and local install

### ISSUE THREAD

**Issue by badsyntax** [swagger-api/swagger-node#351]
I would prefer to keep my dependencies local to the project. Thus, I install swagger as a local devDependency and then hook up swagger via npm scripts:

```json
"scripts": {
  "edit": "swagger project edit",
  "test": "swagger project test"
}
```

This works fine for npm@v2, but does not work for npm@3 because of the way packages are nested (or rather, not nested) in `node_modules`.

The problem lines are here:

* https://github.com/swagger-api/swagger-node/blob/3a000dcc7d0c3c907b60dc0f3efc8e04a3cb3b04/config/index.js#L27
* https://github.com/swagger-api/swagger-node/blob/3a000dcc7d0c3c907b60dc0f3efc8e04a3cb3b04/config/index.js#L35

`node_modules` is no longer nested with npm@3, thus those paths do not exist, which results in a "Cannot GET /" error from connect. 

I'm unclear of an elegant solution here.

**Comment by badsyntax** [comment]
A temporary solution/hack is to define the nested dependencies via a npm-shrinkwrap.json file:

```json
{
  "name": "my-project",
  "version": "1.0.0",
  "dependencies": {
    "swagger": {
      "version": "0.7.5",
      "from": "swagger@>=0.7.5 <0.8.0",
      "resolved": "https://registry.npmjs.org/swagger/-/swagger-0.7.5.tgz",
      "dependencies": {
        "swagger-editor": {
          "version": "2.9.8",
          "from": "swagger-editor@>=2.9.2 <3.0.0",
          "resolved": "https://registry.npmjs.org/swagger-editor/-/swagger-editor-2.9.8.tgz"
        }
      }
    }
  }
}
```

**Comment by swege** [comment]
Just had the exact same problem, the patch works for me perfectly. Thanks!

**Comment by at15** [comment]
NOTE: since the merged pr is still not in any released version, you need to change your `package.json`

````
"devDependencies": {
    "swagger": "git+https://github.com/swagger-api/swagger-node.git#172e1c7659e795fbf792e04ff69499e614858a7f"
  }
````

Ref: http://stackoverflow.com/questions/14187956/npm-install-from-git-in-a-specific-version

**Comment by iThinker** [comment]
How to use it? I've put link to git in dev dependencies. It install swagger, but when I try to run it, I get `Error: Cannot find module 'swagger-editor'`.

**Comment by Den-dp** [comment]
@at15 this will not work because `swagger-editor` don't have `main` field in `package.json` or `index.js` file in root.

Here you can read more about how `require.resolve()` works: https://nodejs.org/api/modules.html#modules_all_together

**Comment by nuarhu** [comment]
Confirming that it does not work:

package.json:

```
  "devDependencies": {
    "swagger": "git+https://github.com/swagger-api/swagger-node.git#172e1c7659e795fbf792e04ff69499e614858a7f"
  },

```

And the error when running `swagger project edit`:

```
> swagger project edit

module.js:338
    throw err;
          ^
Error: Cannot find module 'swagger-editor'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.require.resolve (module.js:388:19)
    at Object.<anonymous> (/Users/ca/devel/git/billigerdoc/node_modules/swagger/config/index.js:35:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/ca/devel/git/billigerdoc/node_modules/swagger/lib/util/browser.js:19:14)

```

No luck with the shrinkwrap work around, so far. Maybe because I haven't installed swagger globally and am running the project edit call via `npm run`?

I've also tried to install `swagger-editor` explicitly but that didn't change anything (same error).

**Comment by iThinker** [comment]
I put empty `index.js` in `swagger-editor` folder. You may automate it in you npm scripts.

**Comment by ronkot** [comment]
Another temporary solution is to overwrite the swagger editor directory using environment variables like so:

`swagger_swagger_editorDir=node_modules/swagger-editor swagger project edit`

Works for me at last.

**Comment by badsyntax** [comment]
@ronkot Thanks for this nice little fix! Hopefully the original change will be released at some point.

**Comment by Nasdan** [comment]
@ronkot Thanks for this, It works for me too. But only one question:
Why do you know that is `swagger_swagger_editorDir` instead of other one? Where is this variable defined?

Thank you again.

**Comment by ronkot** [comment]
@Nasdan This does not sem to be documented behavior, but I found that file [config/index.js](https://github.com/swagger-api/swagger-node/blob/8e53f8cdabe8fe38f571cdaae5738b42a0005fcd/config/index.js#L33) contains objet `config.swagger`, which holds all the config data. This data is then [overwritten](https://github.com/swagger-api/swagger-node/blob/8e53f8cdabe8fe38f571cdaae5738b42a0005fcd/config/index.js#L65) if correct environment variables are set. (The overwriting function was a bit pain to reverse engineer :-D)

**Comment by Nasdan** [comment]
Wow nice work, I didn't see overwritten function code. Thanks :)

**Comment by phiphamuet** [comment]
Simple edit config/index.js in swagger module in local folder node_modules. Change
`rootDir: path.resolve(__dirname, '..')` to `rootDir: path.resolve(__dirname, '../../..')`
add package.json script 
`"edit": "swagger project edit"`
After that run `npm run edit` to start swagger editor.
