### ISSUE TITLE
Exposing Swagger docs

### ISSUE THREAD

**Issue by ugolas** [swagger-api/swagger-node#362]
Hi,

So, i'm using the swagger-node, and in addition I want to expose themy API's Swagger UI documentation page (with the Try Me! option), so that users of my API be able to play with it during integration.

like if my API is:
http://mydomain/

I'd like something like:
http://mydomain/docs

Kind of expected it to be automatically available in some port, but didnt find any reference to it. Am I missing something or I need to add anything to my code?

Thanks!

**Comment by LK1103** [comment]
Same problem! I cannot find the docs.
Any advice?

**Comment by longzhiyou** [comment]
``` javascript
SwaggerExpress.create(config, function(err, swaggerExpress) {
  if (err) { throw err; }

  // Serve the Swagger documents and Swagger UI
  app.use(swaggerExpress.runner.swaggerTools.swaggerUi());



  // install middleware
  swaggerExpress.register(app);

  var port = process.env.PORT || 10010;
  app.listen(port);

  if (swaggerExpress.runner.swagger.paths['/hello']) {
    console.log('try this:\ncurl http://127.0.0.1:' + port + '/hello?name=Scott');
  }
```

### it's ok.
