### ISSUE TITLE
How to obtain req.params?

### ISSUE THREAD

**Issue by dorongrinstein** [swagger-api/swagger-node#367]
I specify a path in the Swagger.yaml:

paths:
   /foo/{user}:
      x-swagger-router-controller: fooHandler
      .
      .
      post:
         parameters:
         - name: "user"
           in: "path"
           .

But when I inspect the request object: req.params, I get {}
I pass a valid user.

**Comment by dorongrinstein** [comment]
I figured out how to obtain the parameter value:

console.log(req.swagger.params.user.value);

**Comment by martinbedouret** [comment]
thanks, it was useful
