### ISSUE TITLE
Facing error while running --> npm install -g swagger

### ISSUE THREAD

**Issue by raghala** [swagger-api/swagger-node#372]
[raghala@localhost ~]$ npm install -g swagger
npm WARN deprecated URIjs@1.16.1: package renamed to "urijs" (lower-case), please update accordingly
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v6.0. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN optional dep failed, continuing fsevents@1.0.11
npm ERR! Linux 3.10.0-123.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "swagger"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! path ../lib/node_modules/swagger/bin/swagger.js
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, symlink '../lib/node_modules/swagger/bin/swagger.js'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, symlink '../lib/node_modules/swagger/bin/swagger.js']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '../lib/node_modules/swagger/bin/swagger.js' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/raghala/npm-debug.log

**Comment by herghost** [comment]
Have you tried running it under sudo?

sudo npm install -g swagger

**Comment by raghala** [comment]
Yup, Tried that way also facing command not found

[raghala@localhost teamforge_core]$ sudo npm install -g swagger
[sudo] password for raghala: 
sudo: npm: command not found

**Comment by raghala** [comment]
Could anyone help me..!

**Comment by herghost** [comment]
It looks like you have installed npm for local user only, your options as far as I am aware are to either install npm again with sudo, or just install swagger without the -g lobal flag in your working directory,

**Comment by raghala** [comment]
Yep ur correct @herghost, How can i set the path globally..?

**Comment by raghala** [comment]
Fixed the issue @herghost , but want to generate outcome as html. I don't see any tools, Could you please help me?

**Comment by herghost** [comment]
I can't on that one I am afraid, you are probably better closing this ticket and opening a new one with your question.

**Comment by cmario92** [comment]
I am having the same issue and calling npm install swagger (without the -g lobal ) is not working. any suggestions?

**Comment by dan-nl** [comment]
you can also try:
`npm i -g swagger-api/swagger-node`

**Comment by lubegasimon** [comment]
- Reinstall npm with a node version manager (recommended)
 or 
- Manually change npm’s default directory

1. _*Using node version manager (nvm)*_ 

 To install or update nvm, you can use the install script using cURL:
    `curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash`

or Wget:
    `wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash`

*Note:* On Linux, after running the install script, if you get `nvm: command not found` or see no feedback from your terminal after you type:

`command -v nvm`

simply close your current terminal, open a new terminal, and try verifying again expect the output to be `nvm`

*Usage*

To download, compile, and install the latest release of node, do this:

`nvm install node # "node" is an alias for the latest version`

To install a specific version of node:

`nvm install 6.14.4 # or 10.10.0, 8.9.1`, etc

You can list available versions using ls-remote:

`nvm ls-remote`

And then in any new shell just use the installed version:

`nvm use node`

Or you can just run it:

`nvm run node --version`

**Comment by lubegasimon** [comment]
- Reinstall npm with a node version manager (recommended),

or

   - Manually change npm’s default directory

1. **Reinstall npm with a node version manager (nvm)**

To install or update nvm, you can use the install script using cURL:

`curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash`

or Wget:

`wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash`

**Note:** On Linux, after running the install script, if you get nvm: command not found or see no feedback from your terminal after you type:

`command -v nvm`

simply close your current terminal, open a new terminal, and try verifying again expecting the output to be `nvm` after running `command -v nvm` .

**Usage**

To download, compile, and install the latest release of node, do this:

`nvm install node # "node" is an alias for the latest version`

To install a specific version of node:

`nvm install 6.14.4 # or 10.10.0, 8.9.1, etc`

You can list available versions using ls-remote:

`nvm ls-remote`

And then in any new shell just use the installed version:

`nvm use node`

Or you can just run it:

`nvm run node ### --version`

**And after following the above guide lines, reinstall `swagger` following the installation guide [here](https://scotch.io/tutorials/speed-up-your-restful-api-development-in-node-js-with-swagger)**

**And for details / reference, follow [this](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) appropriately**
