### ISSUE TITLE
GET request json body always fail schema validation

### ISSUE THREAD

**Issue by clarke07** [swagger-api/swagger-node#386]
I really don't understand this.
For POST method, it's ok. If I set a schema through swagger.yaml and set some default value, it's fine. But when I do the same for GET method, the schema validation fails even if I copied the body through swagger UI (which was generated from swagger.yaml).

for example in swagger.yaml:
```
paths:
  x-swagger-router-controller: userController
  /users:
    get:
      operationId: getUser
      parameters:
        - name: body
        - in: body
        - schema:
           $ref: "#/definitions/userGetBody"
      responses:
          ......

definitions:
  userGetBody:
    required:
      - username
      - password
    properties:
        username:
           type: string
           example: Foo
        password:
           type: string
           example: Bar
```
When I do
```
curl -X GET --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{
  "username": "Foo",
  "password": "Bar"
}' 'http://192.168.99.100/api/v1/users'
```
I just got:
```
{
  "message": "Request validation failed: Parameter (body) failed schema validation",
  "code": "SCHEMA_VALIDATION_FAILED",
  "failedValidation": true,
  "results": {
    "errors": [
      {
        "code": "OBJECT_MISSING_REQUIRED_PROPERTY",
        "message": "Missing required property: password",
        "path": []
      },
      {
        "code": "OBJECT_MISSING_REQUIRED_PROPERTY",
        "message": "Missing required property: username",
        "path": []
      }
    ],
    "warnings": []
  },
  "path": [
    "paths",
    "/users",
    "get",
    "parameters",
    "0"
  ],
  "paramName": "body"
}
```
Even if I remove that `required` part, it will pass the validation but I cannot retrieve the data just like I did for POST request:
`let username = req.body.username`

**Comment by fehguy** [comment]
Get methods do NOT allow post bodies in Swagger, swagger-node, and arguably in any HTTP service.  While they are not explicitly forbidden by the HTTP specification, servers _are_ explicitly required to ignore the body being passed.  So, if you want to use a GET operation, you have to use query, header, path parameters.  If you want to pass a body, you must use post.
