### ISSUE TITLE
Error : "basePath: String does not match pattern"

### ISSUE THREAD

**Issue by iN3O** [swagger-api/swagger-node#395]
I am getting error 

> # /basePath: String does not match pattern ^/:

Here is my api/swagger.json file fields

```
  "swagger": "2.0",
  "info": {
    "title": "C",
    "description": "A",
    "version": "1.0.0"
  },
  "produces": ["application/json"],
  "host": "http://localhost:8080",
  "basePath": "/",

```

**Comment by HugoPB** [comment]
The swagger spec says the host can only be a hostname or ip address. It does not support path.
If you want to use a subdirectory then look into the basePath property.
