### ISSUE TITLE
Support for nullable fields

### ISSUE THREAD

**Issue by RodH257** [swagger-api/swagger-node#399]
I'm attempting to use Swagger Node to specify & validate my API. I'm enjoying the workflow of using the editor, then adding my code, and having it all flow through nicely. However, I have the requirement that I need to be able to accept `null` for fields that aren't required. I want to be able to return a full JSON model with all keys, but set 'null' for fields that are explicitly empty. This has a different meaning to a missing key in the model.

For example I want to return:
```
{ 
  id: 123,
  description: "string",
  date_sent: null
}
```
when there is no `date_sent` yet. I don't want to delete that key from my JSON.

My problem is that if I send through or return null for a non-required field that is normally a string, it fails the request/response validation. Normally in JSON schema I would use anyOf to solve this, but I can't seem to get that working in the swagger editor? My understanding is that the swagger spec doesn't really support that. There is discussion on https://github.com/OAI/OpenAPI-Specification/issues/229 about this, which seems to indicate the spec wont' support it, but that people should consider adding a vendor specific override to support this. 

So my question is, what is the recommended way to create an API that accepts a property with an explicit 'null' value. Or is that just simply impossible using swagger-node? I don't really care if my documentation doesn't indicate that its nullable or not, I just want the validation to pass. 

If there is no recommended way, could we consider adding a `x-nullable: true` extension? As this issue is a total blocker for my API...

**Comment by RodH257** [comment]
I've found out that it does in fact support it (thanks to this SO post http://stackoverflow.com/questions/38139657/nullable-fields-in-swagger-on-node-js/38140597#38140597) 

For reference, to do this, you should update your 'type' to be an array, including `'null'` (must have the quotes), ie:
```
type:
 - string
 - 'null'
```

Then to get it to show in the example values, you can add a `default` value

**Comment by webron** [comment]
That's an invalid spec, for what it's worth. You can have multiple types, and unfortunately, the spec simply does not support `null`. See https://github.com/OAI/OpenAPI-Specification/issues/229.

**Comment by RodH257** [comment]
yeah thats what I was getting at in my original issue - there's  no support for it in the spec (which is very unfortunate) and the discussion on that issue just seems to say we should implement a vendor-specific extension for nulls in the meantime. Seems that instead of using the `x-nullable` suggestion in that issue, swagger-node supports multiple types. 

Perhaps it should be changed to be a more standard compatible style instead of having multiple types, but I'm very happy that there's a way to do it otherwise I wouldn't be able to use the framework at all

**Comment by sylwit** [comment]
I agree with @RodH257 , there is a lot of discussion about supporting null type and that's very unfortunate that no solution is provided.

@webron maybe for making all those discussions becoming useless you can explain how do you write your model in your API or provide examples ?

```
definitions:
  User:
    type: object
    properties:
      id:
        type: string
        format: uuid
      deletedAt:
#        type: [ string, "null" ]
        type: string
        format: date-time
```

Swagger-node fails if you return a User model because if deleted is null then the model doesn't match. This seems to be a basic definition

Thank you

**Comment by webron** [comment]
@sylwit there's really no way of doing it. Just like there's no full support of JSON Schema in general, and just as you can't overload operations using query parameter as a discriminator - the spec simply doesn't support it. And yes, as a result it means some APIs cannot be represented. 

I can't really go into specific cases without knowing the details. In the example you shared, it looks like just not sending the `deletedAt` property is enough (again, don't really know your use case).

**Comment by sylwit** [comment]
Thank you for you answer @webron 

If I took the deletedAt example it's because you don't send it, but when you fetch a result from a mysql database, your object contains this field with a null value which is totally correct but doesn't pass the validation.

Maybe it works better with non relationnal database but one more time you send a null value for deleting a property even in noSQL.

I'd like to see real case of swagger because I can't figure out how you can create an API definition with functions which looks so basic and inevitable

**Comment by RodH257** [comment]
It seems like the workaround I mentioned above:
- string
- 'null'

won't work for objects, ie if you try to do:
- object
- 'null'

to say that you can specify a sub-object as null, it will fail. 

This could be solved with an x-nullable extension as well I'd imagine, which seems to be what a few other frameworks are considering.

**Comment by irufus** [comment]
Can't believe I'm having hours of discussion over this with co-workers one particular issue and how to work-around it because swagger-express middleware still uses 2.0

**Comment by MohdTalib368** [comment]
{
  "workOrderID": 0,
  "workOrderNumber": "123554",
  "description": "string",
  "workStartedDate": "2020-04-10T10:15:25.508Z",
  "additionalDetails": "string",
  "actualDowntime": 0,
  "isPrinted": true,
  "workOrderMasterId": 0,
  "scheduleId": 0,
  "assetId": 0,
  "customerLocationId": 0,
  "locationId": 0,
  "stockroomPartId": 0,
  "priorityId": 0,
  "workOrderStatusId": 0,
  "maintenanceCodeId": 0,
  "workTypeId": 0,
  "costCenterId": 0,
  "shiftId": 0,
  "workOrderRequesterId": 0,
  "assignedToEmployeeId": 0,
  "requestNumber": "string",
  "activationDate": "2020-04-10T10:15:25.508Z",
  "requiredDate": "2020-04-10T10:15:25.508Z",
  "completionDate": "2020-04-10T10:15:25.508Z",
  "lastPrintDate": "2020-04-10T10:15:25.508Z",
  "emailTo": "string",
  "emailCc": "string",
  "emailSubject": "string",
  "emailBody": "string",
  "autoPrint": true,
  "autoEmail": true,
  "autoSendToMobile": true,
  "kitsRequired": true,
  "kitsCompleted": true,
  "estimatedDowntime": 0,
  "modifiedTimestamp": "2020-04-10T10:15:25.508Z",
  "modifiedUserName": "string",
  "assetSystemId": 0,
  "miscellaneousLaborCostId": 0,
  "miscellaneousMaterialsCostId": 0,
  "requesterFullName": "string",
  "userField1": "string",
  "userField2": "2020-04-10T10:15:25.509Z",
  "userField3": "string",
  "userField4": "string",
  "userField5": "string",
  "userField6": "string",
  "userField7": "string",
  "userField8": "string",
  "userField9": "string",
  "userField10": "string",
  "userField11": "string",
  "userField12": "string",
  "userField13": "string",
  "userField14": "string",
  "userField15": "2020-04-10T10:15:25.509Z",
  "userField16": "string",
  "userField17": "string",
  "userField18": "2020-04-10T10:15:25.509Z",
  "userField19": "string",
  "userField20": "string",
  "userField21": "string",
  "userField22": "string",
  "userField23": "string",
  "userField24": "string",
  "requesterEmail": "string",
  "confirmEmail": "string",
  "requestedDate": "2020-04-10T10:15:25.509Z",
  "digitalSignatures": "string",
  "project": "string",
  "requesterPhone": "string",
  "locationHierarchy": "string",
  "internalNote": "string",
  "amStepId": 0,
  "abnormalityId": "string",
  "relatedToId": "string",
  "sourceForm": "string",
  "notificationTime": "string",
  "initialWaitTime": "string",
  "diagnosticTime": "string",
  "partWaitingTime": "string",
  "repairingOrReplacementTime": "string",
  "startupTime": "string",
  "totalTime": "string",
  "analysisPerformedDate": "2020-04-10T10:15:25.509Z",
  "countermeasuresDefinedDate": "2020-04-10T10:15:25.509Z",
  "implementationValidatedDate": "2020-04-10T10:15:25.509Z",
  "serviceRequestModeId": 0,
  "problemId": "string",
  "unsafeConditionId": "string",
  "isLookoutRequired": true,
  "addTools": true,
  "printBom": true,
  "riskQuestion": 0,
  "priorities": {
    "priorityId": 0,
    "priorityName": "string",
    "modifiedTimestamp": "2020-04-10T10:15:25.509Z",
    "modifiedUserName": "string",
    "escalationInterval": 0
  }
}

**Comment by MohdTalib368** [comment]
Hi dear, actually this is my swagger data and in this  top second value is mandotry field and all are optional so when we save this data with only mendatory fields then it insert all the field data type but i want all are null value which are optional there. so pls tell me how can i solve this
