### ISSUE TITLE
No clear error handling documentation

### ISSUE THREAD

**Issue by wjagodfrey** [swagger-api/swagger-node#410]
I'm a little perplexed. I cannot seem to find the documentation regarding swagger error handling. I have searched in all the usual places for answers to my questions without delving into the code, combed through the docs, and searched for keywords. All I found were seemingly outdated solutions. Perhaps I missed something.

My problem is - when I get a validation error it comes as an ugly JSON response with my request buffer attached. How do developers opt out, or modify this error object?

I am using a project generated with `swagger project create`, with `express`.

I also want to be able to generate a valid swagger error from within a controller, as we used to be able to do with `swagger-express`. Something like

```
throw swagger.errors.notFound('pet');
```

https://github.com/swagger-api/swagger-node/tree/2.0.x

Where has this functionality gone?

If that fails, I want to handle errors in the express way - with error handling middleware - but this doesn't seem to work.. I want to choose what I surface to API consumers.

And the final thing, is that the swagger error responses are coming back clipped. Example:

```
{"message":"Response validation failed: failed schema validation","code":"SCHE
```

Am I please able to have some help in resolving these issues?

Many thanks,
Wilfred

----------

**EDIT:** I have raised an issue on `swagger-node-runner` regarding two of the above:
https://github.com/theganyo/swagger-node-runner/issues/48

If I can still find some guidance on returning swagger generated errors from controllers that would be a big help.

**Comment by wjagodfrey** [comment]
My truncated error response seems to have been caused by `swagger-express-mw` overwriting the 404 response returned by a line in my controller, that I was using for debugging:

```
return res.status(404).send('No good!');
```

This line was setting the `Content-Length` to 8, after which point `swagger-express-mw` was overwriting the response body with JSON. This JSON response was truncated to 8 characters.

I fixed the issue by returning:

```
return res.status(404).send();
```

After which point I receive the full swagger error.

This seems like poor error handling to me - either allow users to send their own errors, or set `Content-Length` correctly when overwriting user response.

**Comment by cjrd** [comment]
I'm experiencing similar issues.

Error handling/responses are a fundamental part of a good API, and right now, I'm hacking together various work-arounds to achieve error handling with swagger-node. Clear documentation on how to do error handling, e.g. "How do I handle model validation errors and return a reasonable response to my users?", would be awesome :)/

**Comment by wjagodfrey** [comment]
To close, `swagger-node`'s generator installs an old version of `swagger-express-mw`. Update it to the most recent.

Then, handle errors as described in this `swagger-node-runner` release document:
https://github.com/theganyo/swagger-node-runner/releases/tag/v0.6.4

It would be worth having this added to the documentation in some regard. All these nested repos make it very difficult to resolve these questions.

**Comment by ThoWim** [comment]
Hey @wjagodfrey,

how about the **request** validation ? I could not find a clear reference to this either.

**Comment by stv8** [comment]
Did the API change? I am getting an error saying the `on` is not a function on `swaggerExpress.runner`

**Comment by blmalone** [comment]
+1 on the above?

**Comment by ps1dr3x** [comment]
I'm trying to set an handler for the **responseValidationError** event (using **swagger-express-mw v0.7.0**), but it would seem that it is never fired.

Can anyone confirm this?

If you voluntarily pass incorrect parameters i still receive errors like this:

`{"message":"Validation errors","errors":[{"code":"INVALID_REQUEST_PARAMETER","errors":[{"code":"INVALID_FORMAT","message":"Object didn't pass validation for format date-time: ","path":[]}],"in":"query","message":"Invalid parameter (datelt): Object didn't pass validation for format date-time: ","name":"datelt","path":[]}]}`

But the handler callback is never called.

The code is simple:
`
  swaggerExpress.create(global.config, (err, mw) => {
    if (err) throw err

    // Swagger middleware
    mw.register(app)
    mw.runner.on('responseValidationError', (validationResponse, request, response) => {
      console.error(validationResponse.errors)
    })

    // Public folder
    app.use(express.static('public'))

    let port = global.config.http_port
    app.listen(port, () => {
      debugApp('Listening on port %s...', port)
    })
  })
`

Maybe there's something more besides the listener to set up?

**Comment by blmalone** [comment]
I've recently been able to successfully override the `errorHandler` so that I can intercept any failed requests. 

In short: 
Modifying the default.yaml file that tells swagger what features to switch on and off was the trick.

i.e. 
```
    # pipe for all swagger-node controllers
    swagger_controllers:
      #- onError: json_error_handler
      - cors
      - swagger_security
      - _swagger_validate
      - express_compatibility
      - _router
```
You can see that I've commented out swaggers json_error_handler, essentially telling swagger that I'll take it from here, you don't need to handle errors. 
If you do this you must pass your customer handler to swagger, like so...

```
SwaggerExpress.create(config, function (err, swaggerExpress) {
    if (err) {
        throw err;
    }
    // install middleware
    swaggerExpress.register(app);
    app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));
    app.use(errorHandler);

    let port = process.env.PORT || 8443;
    https.createServer(options, app).listen(port, function () {
    });
});

/*
    Intercepting errors detected from the swagger validation. We can return customised errors based on the
    operationId and the err.code. Could move this into it's own js file and export it.
    In the future as the api changes, this may become more difficult to manage. Perhaps default swagger error handling
    should be considered.
 */
function errorHandler(err, req, res, next) {
    let operationId = req.swagger.operation.operationId;
    console.log('err.code: ', err.code);
    console.log('this is the request obj: ', operationId);
    res.status(403).json('Enter whatever error you want here.');
}
```

**Comment by ps1dr3x** [comment]
lol i understood my fault: responseValidationError event regards only **response** validations, while I was trying to intercept **request** validations errors.
Anyway i tried to set a custom handler as shown by @blmalone but continues not to be called, for errors like this:
`{"message":"invalid input syntax for uuid: \"asdasd\""}`

**Comment by oehm-smith** [comment]
This helped me - https://stackoverflow.com/questions/38647242/swagger-tools-error-handler-middleware-not-catching-errors
