### ISSUE TITLE
Running project in production: swagger project start vs. node app.js

### ISSUE THREAD

**Issue by aroach** [swagger-api/swagger-node#414]
Is there a recommendation on whether one should use the `swagger project start` vs `node app.js` to run your app in production?  

Sorry if this is documented somewhere, but couldn't find mention of any tradeoffs.

**Comment by fehguy** [comment]
I suggest using `swagger project start` for development and `node app.js` for proper deployments.

**Comment by aroach** [comment]
Perfect, thanks!

**Comment by aroach** [comment]
@fehguy I'd be happy to add this to the docs.  After looking through the /docs directory, I thought maybe at the end of Quick Start would be appropriate.  Does that seem good?

**Comment by fehguy** [comment]
yes, great

**Comment by aroach** [comment]
cool, done. and thanks for accepting! #415

**Comment by hungitk46** [comment]
i think we can using 

> pm2 start app.js

 proper deployments.

**Comment by maziyarpanahi** [comment]
Is there any reason to not use `node app.js` for both development and production?
