### ISSUE TITLE
How can I use Istanbul coverage ?

### ISSUE THREAD

**Issue by nilovna** [swagger-api/swagger-node#443]
I'd like to be able to have a coverage report using Istanbul, when running `swagger project test`.

I tried:

``` bash
# npm run test:api script is "swagger project test -m" in package.json
$ istanbul cover npm run test:api 
```

The tests run, but no coverage is created.
I have this message after the tests.

```
No coverage information was collected, exit without writing coverage information
```

Is there a way to do this?
Thanks!

**Comment by abekim** [comment]
Hi,

I noticed that `swagger project -m` has the same effect as setting the environment variable `swagger_mockMode=true`. I just incorporated coverage to my project by creating the following npm script:
```swagger_mockMode=true istanbul cover node_modules/.bin/_mocha -- --recursive test/```

I have a counterpart that runs the same script without the environment variable to cover the tests and coverage outside the mock mode as well.

Let me know if this helps!

Best,
Abe

**Comment by nilovna** [comment]
@abekim Thank you Abe, I will give it a try!

**Comment by Headcult** [comment]
Yes, we would want Code Coverage to be a part of Swagger CLI. That would be very useful.

**Comment by simpgeek** [comment]
nyc works fine for me:

`nyc swagger project test`

**Comment by nilovna** [comment]
So this is what I have in my `package.json` and it works fine.
Thanks agin @abekim 

```json
"test": "NODE_ENV=test swagger_mockMode=true nyc --reporter=text-summary mocha --require ./config/mocha.js --recursive test"
```
