### ISSUE TITLE
Can't use class instance as a controller

### ISSUE THREAD

**Issue by Nagogus** [swagger-api/swagger-node#447]
Hi, I am trying to use class instance as a controller. 

```
class MyController {
    get(req, res) { ... }
}
module.exports = new MyController();
```

But it doesn't work and says "Cannot resolve the configured swagger-router handler: my_controller.get". If I change it to plain object then everything is fine. I went through the code and seems it is done intentionally. During creation of `handleCache` router checks if methods are plain objects. What is the reason and is there a way to get around?

**Comment by Nagogus** [comment]
Solved by upgrading swagger-express-mw module to the latest version.
Follow upgrade section in the [release](https://github.com/theganyo/swagger-node-runner/releases/tag/v0.6.0) of swagger-node-runner

**Comment by agalazis** [comment]
@Nagogus  This is not true still eg. if you try to access `this` for (for example to access injected values it won't work) Other than that why would you export an instance of it and not use a static function?
