### ISSUE TITLE
Typescript or es6 integration

### ISSUE THREAD

**Issue by jeffswitzer** [swagger-api/swagger-node#451]
I'm exploring using this to build my next node api but prefer to work with typescript. Is there is a way to use this with typescript or es6?

**Comment by abekim** [comment]
If I'm not mistaken, whether your project supports ES6 standard or not depends on your version of Node.js. Personally, I've been using Node.js 6.9.1 with `swagger-node` without any issues with ES6 syntax.

Best of luck, @jeffswitzer!

**Comment by jeffswitzer** [comment]
@abekim good point :) I upgraded my node version and am now able to use es6 with swagger-node.
