### ISSUE TITLE
Editor does not work in hello world tutorial

### ISSUE THREAD

**Issue by adrianmcli** [swagger-api/swagger-node#457]
Basically, I came across a problem very similar to #351. I installed swagger using `npm install -g swagger`, created a hello-world app, and tried to launch the editor.

Unfortunately, it didn't work until I had to explicitly install `swagger-editor` myself (using `npm install --save-dev swagger-editor`). It seems strange to me that `swagger-editor` isn't automatically installed during the app creation phase. If that is the intended effect, perhaps the README instructions should be updated to show that.

**Comment by phiphamuet** [comment]
see my answer at last #351

**Comment by fehguy** [comment]
thanks @phiphamuet, closing this...
