### ISSUE TITLE
swagger project edit - cannot get /

### ISSUE THREAD

**Issue by splitbrain** [swagger-api/swagger-node#480]
I'm completely new to the project and was just following the 5 steps in the README. However step 3 fails. 

The server starts and opens my browser at `http://127.0.0.1:34407/#/edit` however all I get is a 404 with a `Cannot GET /` error message.

Maybe there's a step missing in the README?

In case it matters:

```
$ node --version
v7.7.2
$ npm --version
4.4.1
$ uname -a
Linux perd 4.10.1-1-ARCH #1 SMP PREEMPT Sun Feb 26 21:08:53 UTC 2017 x86_64 GNU/Linux
```

**Comment by DanielRamosAcosta** [comment]
I was also getting this error becouse I had `swagger` installed locally as devDependency, but it seems that it also needs `swagger-editor` package in order to work.

**Comment by splitbrain** [comment]
That's it! I installed swagger-edit and it worked. Thanks!

**Comment by dwmkerr** [comment]
Good spot @splitbrain. Might be better if a sensible error message is shown in this case though, would it be worth re-opening this issue and updating it to something like:

**If swagger-editor is not installed, show a sensible error message**

WDYT?

**Comment by saisankargochhayat** [comment]
I guess we can make a better error message as @dwmkerr suggests.

**Comment by rmariuzzo** [comment]
I just added it with: `npm install --save-dev swagger-editor` and all work as expected.

**Comment by DanielRamosAcosta** [comment]
I think the correct way to proceed is add `swagger-editor` as peer dependency.

**Comment by ryanmilvenan** [comment]
I added swagger-editor and still get the cannot GET /, any thoughts? Fresh project create and added swagger editor.

**Comment by subos2008** [comment]
Given the codebase is auto-generated - why not just add it the the devDependencies? and also to the README that you need to install devDeps?

**Comment by subos2008** [comment]
Also the readme says to install swagger globally, in which case the editor seems to need to be installed globally as well.

Great project guys - thanks for all your contributions!

**Comment by jonathanfallon** [comment]
Installing `swagger-editor` globally solved it for me.

`sudo yarn global add swagger-editor`

Tried it as a `devDependencies` and didn't work. Once the package was installed globally, it worked fine with a new project (`swagger project create hello-world`)

**Comment by imcspandey** [comment]
I installed both swagger and swagger-editor globally but it didn't work. I am trying to install on windows 10 :(
