### ISSUE TITLE
Last release 2 years ago?

### ISSUE THREAD

**Issue by bootstraponline** [swagger-api/swagger-node#517]
It looks like the last release was in 2015? Any plans for a new release?

> https://github.com/swagger-api/swagger-node/releases
> https://www.npmjs.com/package/swagger

**Comment by drej1** [comment]
That's a really good question. On top of that there is OAS 3.0 already out :/

This tool is really good, but it's getting really outdated I think... :(

**Comment by webron** [comment]
Sorry for the delayed response. Please see #514 for more information, but the short answer is that we do plan on new releases.
