### ISSUE TITLE
Write configuration in JSON format

### ISSUE THREAD

**Issue by sauravpandit** [swagger-api/swagger-node#523]
Right now the framework is using YAML for configuring both the framework and application.
According to open API specification we can use JSON. It will be great if this framework support JSON formatted document. Please inform me whether it possible or not.

**Comment by msjoshi** [comment]
I have the same question. I hope there is a way to use JSON files for configuration.

**Comment by sauravpandit** [comment]
I think we have use json to yaml converter.
