### ISSUE TITLE
Upgrade to latest Swagger Version 

### ISSUE THREAD

**Issue by AbhishekBatwara** [swagger-api/swagger-node#533]
I am confused while asking this question as its mentioned **swagger 3.0** version is released but It looks like internally this modules uses **swagger 1.2** version, is there a way we can update to latest version so that latest API specs can be used.
Any help is appreciated.

**Comment by webron** [comment]
There's some confusion in terminology. Swagger 1.2 is a version of the spec. This tool uses Swagger 2.0 of the spec. There's no Swagger 3.0 - the spec itself has been renamed and it is now known as OpenAPI 3.0.0. "Swagger 3.0" is often related to swagger-ui or swagger-editor, which are not the spec but tools around it. As for what's coming regarding OAS3 support - you can read about it in #514. We currently don't have the capacity to upgrade this tool to use swagger-ui/editor 3.X.

**Comment by AbhishekBatwara** [comment]
@webron Thanks for the clarification.
Can I specify swagger version as 2.0 while configuring the swagger or this tool internally uses 2.0 only. I am confused as in the code () it is mentioned swaggerVersion as 1.2 and 2.0 both. 
or its the swaggerUI tool which should have latest version which you mentioned above to load the latest API specs.
The intention is to use latest Api specs parameters so that I can have better API documentation.

**Comment by AbhishekBatwara** [comment]
@webron When I am hitting my swagger json its listing the output as:
{"apiVersion":"2.0.0","swaggerVersion":"1.2","apis":[{"path":"/auth"}]

It seems like its picking the swagger version as 1.2. Can I update it to 2.0, where I can use latest tags and other property.
